/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 * Copyright (c) 2013, MPL CodeInside http://codeinside.ru
 */

package ru.codeinside.gws3564c.enclosure.gkn.ui;


import org.junit.Before;
import org.junit.Test;
import ru.codeinside.gws.api.ExchangeContext;
import ru.codeinside.gws3564c.DummyContext;
import ru.codeinside.gws3564c.EnclosureBuilderFactory;
import ru.codeinside.gws3564c.enclosure.EnclosureRequestBuilder;

import java.util.Date;

public class CadastralPasportUIIntegrationTest {
  private ExchangeContext context;

  @Before
  public void setUp() throws Exception {
    context = new DummyContext();
  }

  @Test
  public void testShouldBuildEnlosureForGovDeclarantWithoutException() throws Exception {
    fillContextWhenDeclarantIsGovernance();
    EnclosureRequestBuilder enclosureBuilder = EnclosureBuilderFactory.createEnclosureBuilder(context);
    String xml = enclosureBuilder.createEnclosure("7b983700-651d-43d8-bdb4-26dd683df535");
    //System.out.print(xml);
  }

  @Test
  public void testShouldBuildEnclosureForLegalPersonDeclarantWithoutException() throws Exception {
    fillContextWhenDeclarantIsLegalPerson();
    EnclosureRequestBuilder enclosureBuilder = EnclosureBuilderFactory.createEnclosureBuilder(context);
    String xml = enclosureBuilder.createEnclosure("7b983700-651d-43d8-bdb4-26dd683df535");
   // System.out.print(xml);
  }

  @Test
  public void testShouldBuildEnclosureForPersonDeclarantWithoutException() throws Exception {
    fillContextWhenDeclarantIsPerson();
    EnclosureRequestBuilder enclosureBuilder = EnclosureBuilderFactory.createEnclosureBuilder(context);
    String xml = enclosureBuilder.createEnclosure("7b983700-651d-43d8-bdb4-26dd683df535");
     System.out.print(xml);
  }

  private void fillContextWhenDeclarantIsPerson() {
    context.setVariable("agentStreetName", "Южная");
    context.setVariable("cadastralPassportLocationLevel2Value", "");
    context.setVariable("paymentDoc_Type_1", "555001000000");
    context.setVariable("declLocationLocationLevel1Value", "1");
    context.setVariable("declLocationLocalityType", null);
    context.setVariable("cadastralPassportSovietVillageType", null);
    context.setVariable("cadastralPassportCLADR", "");
    context.setVariable("cadastralPassportUrbanDistictName", "");
    context.setVariable("cadastralPassportLocationLevel3Value", "");
    context.setVariable("smevInitialRegDate", new Date());
    context.setVariable("cadastralPassportCityName", "Калуга");
    context.setVariable("declPersonSNILS", "112-233-332 33");
    context.setVariable("declLocationUrbanDistictName", "");
    context.setVariable("agentLocationLevel2Value", "");
    context.setVariable("agentCityName", "Калуга");
    context.setVariable("appliedADocumentNumber_1", "12212212");
    context.setVariable("declLocationDCity", "г");
    context.setVariable("cadastralPassportRegion", "40");
    context.setVariable("cadastralPassportPostalCode", "");
    context.setVariable("Legal", "Юридические лица");
    context.setVariable("declLegalPersonPhone", "12121212");
    context.setVariable("agentSovietVillageName", "");
    context.setVariable("cadastralPassportDistrictType", null);
    context.setVariable("okato", "60000000000");
    context.setVariable("paymentADocumentOriginalQuantitySheet_1", "1");
    context.setVariable("paymentADocumentOriginalQuantity_1", "1");
    context.setVariable("cadastralPassportLocationOther", "");
    context.setVariable("declPersonEmail", "test@test.com");
    context.setVariable("declLegalPersonRegDate", null);
    context.setVariable("agentRegion", "40");
    context.setVariable("declPersonFIOFirst", "Иван");
    context.setVariable("cadastralPassportLocationApartmentValue", "1");
    context.setVariable("cadastralPassportOKATO", null);
    context.setVariable("procedureId", "8");
    //context.setVariable("declPersonSex", "M");
    context.setVariable("appliedADocumentIssue_1", "УВД");
    context.setVariable("agentLocationLevel2Type", null);
    context.setVariable("agentLocationLevel3Value", "");
    context.setVariable("declLocationLocationOther", "");
    context.setVariable("declLocationLocationApartmentType", "кв");
    context.setVariable("paymentDate_1", new Date());
    context.setVariable("declPersonPDocumentSeries", "1222");
    context.setVariable("declLocationLocationLevel2Type", null);
    context.setVariable("declPersonPDocumentIssueOrgan", "УВД");
    context.setVariable("cadastralPassportStreetName", "Южная");
    context.setVariable("agentDCity", "г");
    context.setVariable("paymentSum_1", "10000");
    context.setVariable("agentLocationLevel1Value", "1");
    context.setVariable("agentLocationOther", "");
    context.setVariable("cadastralPassportLocationLevel1Value", "1");
    context.setVariable("agentPhone", "123121");
    context.setVariable("agentUrbanDistictType", null);
    context.setVariable("declLocationDistrictType", null);
    context.setVariable("agentFIOFirst", "Антон");
    context.setVariable("agentLocalityName", "");
    context.setVariable("declPersonPhone", "12212212221");
    context.setVariable("payment", "1");
    context.setVariable("agentLocalityType", null);
    context.setVariable("smevTest", "Первичный запрос");
    context.setVariable("declLocationSovietVillageType", null);
    context.setVariable("agentSNILS", "112-233-332 33");
    context.setVariable("declLocationLocationLevel2Value", "");
    context.setVariable("Individuals", "Индивидуальные предпринематели");
    //context.setVariable("declPersonMarriageStatus", "женат");
    context.setVariable("procedureTypeName", "0");
    context.setVariable("agentPDocumentSeries", "1221");
    context.setVariable("agentDStreets", "ул");
    context.setVariable("cadastralPassportLocationApartmentType", "кв");
    context.setVariable("declKind", "357007000000");
    context.setVariable("declLocationLocationLevel3Value", "");
    context.setVariable("declGovernancePhone", "12342323");
    context.setVariable("enclosure_request_type", "CADASTRAL_PASSPORT");
    context.setVariable("paymentFIOPayer_1", "ФИО плательщика");
    context.setVariable("agentCLADR", "");
    context.setVariable("agentPDocumentDate", new Date());
    context.setVariable("declLocationUrbanDistictType", null);
    context.setVariable("agentLocationLevel3Type", null);
    context.setVariable("appliedADocumentOriginalQuantity_1", "1");
    context.setVariable("declLegalPersonEmail", "tesst@rerer.com");
    context.setVariable("agentPostalCode", "");
    context.setVariable("cadastralPassportSovietVillageName", "");
    context.setVariable("declLegalPersonINN", "12343434");
    context.setVariable("smevInitialRegNumber", "137562864121229299");
    context.setVariable("declPersonPDocumentCode", "008001001000");
    context.setVariable("declPersonPDocumentNumber", "121212");
    context.setVariable("cadastralPassportDStreets", "ул");
    context.setVariable("paymentOKATO_1", null);
    context.setVariable("agentUrbanDistictName", "");
    context.setVariable("declLocationLocationNote", "");
    context.setVariable("paymentSettlement_Account_1", "1234345546565565");
    context.setVariable("appliedADocumentCode_1", "008001001000");
    context.setVariable("cadastralPassportLocationNote", "");
    context.setVariable("paymentBank_Name_1", "Сбербанк");
    context.setVariable("agentLocationApartmentValue", "1");
    context.setVariable("declLocationOKATO", null);
    context.setVariable("declLocationLocationApartmentValue", "1");
    context.setVariable("declLocationDistrictName", "");
    context.setVariable("declLocationDStreets", "ул");
    context.setVariable("cadastralPassportLocationLevel2Type", null);
    context.setVariable("declGovernanceCode", "007001001001");
    context.setVariable("cadastralPassportDCity", "г");
    context.setVariable("cadastralPassportLocalityName", "");
    context.setVariable("agentLocationLevel1Type", "д");
    context.setVariable("cadastralPassportDistrictName", "");
    context.setVariable("agentFIOPatronymic", "Антонович");
    context.setVariable("agentDistrictName", "");
    context.setVariable("cadastralPassportLocationLevel1Type", "д");
    context.setVariable("declGovernanceName", "Пенсионный фонд");
    context.setVariable("serviceId", "3");
    context.setVariable("declPersonPDocumentDate", new Date());
    context.setVariable("declLocationStreetName", "Южная");
    context.setVariable("appliedADocumentDate_1", new Date());
    context.setVariable("declarantLogin", "test");
    context.setVariable("cadastralPassportLocationLevel3Type", null);
    context.setVariable("declLocationRegion", "40");
    context.setVariable("agentPDocumentCode", "008001001000");
    context.setVariable("declLocationSovietVillageName", "");
    context.setVariable("declLocationLocationLevel1Type", "д");
    context.setVariable("oktmo", "01234567");
    context.setVariable("declLegalPersonName", "Точка");
    context.setVariable("declLegalPersonOGRN", "1212122");
    context.setVariable("paymentNumber_1", "1");
    context.setVariable("cadastralPassportObjKind", "002001001000");
    context.setVariable("cadastralPassportLocalityType", null);
    context.setVariable("cadastralPassportUrbanDistictType", null);
    context.setVariable("declLocationPostalCode", "");
    context.setVariable("agentEmail", "reeer@erere.com");
    context.setVariable("agentPDocumentNumber", "121212");
    context.setVariable("agentPDocumentIssueOrgan", "УВД");
    context.setVariable("declarantType", "PERSON");
    context.setVariable("appliedADocumentDesc_1", "нет");
    context.setVariable("agentOKATO", null);
    context.setVariable("paymentBIC_1", "123456675");
    context.setVariable("agentFIOSurname", "Антонов");
    context.setVariable("agentSovietVillageType", null);
    context.setVariable("declLocationLocalityName", "");
    context.setVariable("agentDistrictType", null);
    context.setVariable("requestType", "558103080000");
    context.setVariable("declLocationCLADR", "");
    context.setVariable("agentLocationNote", "");
    context.setVariable("Physical", "Физические лица");
    context.setVariable("agentKind", "356002000000");
    context.setVariable("agentLocationApartmentType", "кв");
    context.setVariable("declLocationCityName", "Калуга");
    context.setVariable("appliedADocumentOriginalQuantitySheet_1", "1");
    context.setVariable("applied", "1");
    context.setVariable("appliedADocumentName_1", "Паспорт гражданина РФ");
    context.setVariable("declPersonFIOPatronymic", "Иванович");
    context.setVariable("declPersonFIOSurname", "Иванов");
    context.setVariable("declLocationLocationLevel3Type", null);
  }

  private void fillContextWhenDeclarantIsLegalPerson(){
    context.setVariable("agentStreetName", "Южная");
    context.setVariable("cadastralPassportLocationLevel2Value", "");
    context.setVariable("paymentDoc_Type_1", "555001000000");
    context.setVariable("declLocationLocationLevel1Value", "1");
    context.setVariable("declLocationLocalityType", null);
    context.setVariable("cadastralPassportSovietVillageType", null);
    context.setVariable("cadastralPassportCLADR", "");
    context.setVariable("cadastralPassportUrbanDistictName", "");
    context.setVariable("cadastralPassportLocationLevel3Value", "");
    context.setVariable("smevInitialRegDate", new Date());
    context.setVariable("cadastralPassportCityName", "Калуга");
    context.setVariable("declLocationUrbanDistictName", "");
    context.setVariable("declPersonSNILS", "112-233-332 33");
    context.setVariable("agentLocationLevel2Value", "");
    context.setVariable("agentCityName", "Калуга");
    context.setVariable("appliedADocumentNumber_1", "12212212");
    context.setVariable("declLocationDCity", "г");
    context.setVariable("cadastralPassportRegion", "40");
    context.setVariable("cadastralPassportPostalCode", "");
    context.setVariable("Legal", "Юридические лица");
    context.setVariable("declLegalPersonPhone", "12121212");
    context.setVariable("agentSovietVillageName", "");
    context.setVariable("cadastralPassportDistrictType", null);
    context.setVariable("okato", "60000000000");
    context.setVariable("paymentADocumentOriginalQuantitySheet_1", "1");
    context.setVariable("paymentADocumentOriginalQuantity_1", "1");
   // context.setVariable("declLegalPersonContactInfo", "212121212");
    context.setVariable("cadastralPassportLocationOther", "");
    context.setVariable("declPersonEmail", "test@test.com");
    context.setVariable("declLegalPersonRegDate", new Date());
    context.setVariable("agentRegion", "40");
    context.setVariable("declPersonFIOFirst", "Иван");
    context.setVariable("cadastralPassportLocationApartmentValue", "1");
    context.setVariable("cadastralPassportOKATO", null);
    context.setVariable("procedureId", "8");
    context.setVariable("declPersonSex", "M");
    context.setVariable("appliedADocumentIssue_1", "УВД");
    context.setVariable("agentLocationLevel2Type", null);
    context.setVariable("agentLocationLevel3Value", "");
    context.setVariable("declLocationLocationOther", "");
    context.setVariable("declLocationLocationApartmentType", "кв");
    context.setVariable("paymentDate_1", new Date());
    context.setVariable("declPersonPDocumentSeries", "1222");
    context.setVariable("declLocationLocationLevel2Type", null);
    context.setVariable("declPersonPDocumentIssueOrgan", "УВД");
    context.setVariable("cadastralPassportStreetName", "Южная");
    context.setVariable("agentDCity", "г");
    context.setVariable("paymentSum_1", "10000");
    context.setVariable("agentLocationLevel1Value", "1");
    context.setVariable("agentLocationOther", "");
    context.setVariable("cadastralPassportLocationLevel1Value", "1");
    context.setVariable("agentPhone", "123121");
    context.setVariable("agentUrbanDistictType", null);
    context.setVariable("declLocationDistrictType", null);
    context.setVariable("agentFIOFirst", "Антон");
    context.setVariable("agentLocalityName", "");
    context.setVariable("declPersonPhone", "12212212221");
    context.setVariable("payment", "1");
    context.setVariable("agentLocalityType", null);
    context.setVariable("smevTest", "Первичный запрос");
    context.setVariable("declLocationSovietVillageType", null);
    context.setVariable("agentSNILS", "112-233-332 33");
    context.setVariable("declLocationLocationLevel2Value", "");
    context.setVariable("Individuals", "Индивидуальные предпринематели");
    context.setVariable("declPersonMarriageStatus", "женат");
    context.setVariable("procedureTypeName", "0");
    context.setVariable("agentPDocumentSeries", "1221");
    context.setVariable("agentDStreets", "ул");
    context.setVariable("cadastralPassportLocationApartmentType", "кв");
    context.setVariable("declKind", "357007000000");
    context.setVariable("declLocationLocationLevel3Value", "");
    context.setVariable("declGovernancePhone", "12342323");
    context.setVariable("enclosure_request_type", "CADASTRAL_PASSPORT");
    context.setVariable("paymentFIOPayer_1", "ФИО плательщика");
    context.setVariable("agentCLADR", "");
    context.setVariable("agentPDocumentDate", new Date());
    context.setVariable("declLocationUrbanDistictType", null);
    context.setVariable("agentLocationLevel3Type", null);
    context.setVariable("appliedADocumentOriginalQuantity_1", "1");
    context.setVariable("declLegalPersonEmail", "tesst@rerer.com");
    context.setVariable("agentPostalCode", "");
    context.setVariable("cadastralPassportSovietVillageName", "");
    context.setVariable("declLegalPersonINN", "12343434");
    context.setVariable("smevInitialRegNumber", "137562152022598493");
    context.setVariable("declPersonPDocumentCode", "008001001000");
    context.setVariable("declPersonPDocumentNumber", "121212");
    context.setVariable("cadastralPassportDStreets", "ул");
    context.setVariable("paymentOKATO_1", null);
    context.setVariable("agentUrbanDistictName", "");
    context.setVariable("declLocationLocationNote", "");
    context.setVariable("paymentSettlement_Account_1", "1234345546565565");
    context.setVariable("cadastralPassportLocationNote", "");
    context.setVariable("appliedADocumentCode_1", "008001001000");
    context.setVariable("paymentBank_Name_1", "Сбербанк");
    context.setVariable("agentLocationApartmentValue", "1");
    context.setVariable("declLocationOKATO", null);
    context.setVariable("declLocationLocationApartmentValue", "1");
    context.setVariable("declLocationDistrictName", "");
    context.setVariable("declLocationDStreets", "ул");
    context.setVariable("cadastralPassportLocationLevel2Type", null);
    context.setVariable("declGovernanceCode", "007001001001");
    context.setVariable("cadastralPassportDCity", "г");
    context.setVariable("cadastralPassportLocalityName", "");
    context.setVariable("agentLocationLevel1Type", "д");
    context.setVariable("cadastralPassportDistrictName", "");
    context.setVariable("agentFIOPatronymic", "Антонович");
    context.setVariable("agentDistrictName", "");
    context.setVariable("cadastralPassportLocationLevel1Type", "д");
    context.setVariable("declGovernanceName", "Пенсионный фонд");
    context.setVariable("serviceId", "3");
    context.setVariable("declPersonPDocumentDate", null);
    context.setVariable("declLocationStreetName", "Южная");
    context.setVariable("appliedADocumentDate_1", new Date());
    context.setVariable("declarantLogin", "test");
    context.setVariable("cadastralPassportLocationLevel3Type", null);
    context.setVariable("declLocationRegion", "40");
    context.setVariable("agentPDocumentCode", "008001001000");
    context.setVariable("declLocationSovietVillageName", "");
    context.setVariable("declLocationLocationLevel1Type", "д");
    context.setVariable("oktmo", "01234567");
    context.setVariable("declLegalPersonName", "Точка");
    context.setVariable("declLegalPersonOGRN", "1212122");
    context.setVariable("paymentNumber_1", "1");
    context.setVariable("cadastralPassportObjKind", "002001003000");
    context.setVariable("cadastralPassportLocalityType", null);
    context.setVariable("cadastralPassportUrbanDistictType", null);
    context.setVariable("declLocationPostalCode", "");
    context.setVariable("agentEmail", "reeer@erere.com");
    context.setVariable("agentPDocumentNumber", "121212");
    context.setVariable("agentPDocumentIssueOrgan", "УВД");
    context.setVariable("declarantType", "ORGANISATION");
    context.setVariable("appliedADocumentDesc_1", "нет");
    context.setVariable("agentOKATO", null);
    context.setVariable("paymentBIC_1", "123456675");
    context.setVariable("agentFIOSurname", "Антонов");
    context.setVariable("agentSovietVillageType", null);
    context.setVariable("declLocationLocalityName", "");
    context.setVariable("agentDistrictType", null);
    context.setVariable("requestType", "558103080000");
    context.setVariable("declLocationCLADR", "");
    context.setVariable("agentLocationNote", "");
    context.setVariable("Physical", "Физические лица");
    context.setVariable("agentKind", "356002000000");
    context.setVariable("agentLocationApartmentType", "кв");
    context.setVariable("declLocationCityName", "Калуга");
    context.setVariable("appliedADocumentOriginalQuantitySheet_1", "1");
    context.setVariable("applied", "1");
    context.setVariable("appliedADocumentName_1", "Паспорт гражданина РФ");
    context.setVariable("declLocationLocationLevel3Type", null);
    context.setVariable("declPersonFIOPatronymic", "Иванович");
    context.setVariable("eclPersonFIOSurname", "Иванов");
  }



  private void fillContextWhenDeclarantIsGovernance() {
    context.setVariable("cadastralPassportObjKind", "002001001000");
    context.setVariable("agentStreetName", "Южная");
    context.setVariable("cadastralPassportLocationLevel2Value", "");
    context.setVariable("paymentDoc_Type_1", "555001000000");
    context.setVariable("declLocationLocationLevel1Value", "1");
    context.setVariable("declLocationLocalityType", null);
    context.setVariable("cadastralPassportSovietVillageType", null);
    //context.setVariable("cadastralPassportNumber", "212:212:212:212");
    context.setVariable("cadastralPassportCLADR", "");
    context.setVariable("cadastralPassportUrbanDistictName", "");
    context.setVariable("cadastralPassportLocationLevel3Value", "");
    context.setVariable("smevInitialRegDate", new Date());
    context.setVariable("cadastralPassportCityName", "Калуга");
    context.setVariable("declLocationUrbanDistictName", "");
    context.setVariable("declPersonSNILS", "112-233-332 33");
    context.setVariable("agentLocationLevel2Value", "");
    context.setVariable("agentCityName", "Калуга");
    context.setVariable("appliedADocumentNumber_1", "12212212");
    context.setVariable("declLocationDCity", "г");
    context.setVariable("cadastralPassportRegion", "40");
    context.setVariable("cadastralPassportPostalCode", "");
    context.setVariable("Legal", "Юридические лица");
    context.setVariable("declLegalPersonPhone", "12121212");
    context.setVariable("agentSovietVillageName", "");
    context.setVariable("cadastralPassportDistrictType", null);
    context.setVariable("okato", "60000000000");
    context.setVariable("paymentADocumentOriginalQuantitySheet_1", "1");
    context.setVariable("paymentADocumentOriginalQuantity_1", "1");
   // context.setVariable("declLegalPersonContactInfo", "212121212");
    context.setVariable("cadastralPassportLocationOther", "");
    context.setVariable("declPersonEmail", "test@test.com");
    context.setVariable("declLegalPersonRegDate", null);
    context.setVariable("agentRegion", "40");
    context.setVariable("declPersonFIOFirst", "Иван");
    context.setVariable("cadastralPassportLocationApartmentValue", "1");
    context.setVariable("cadastralPassportOKATO", null);
    context.setVariable("procedureId", "8");
    context.setVariable("declPersonSex", "M");
    context.setVariable("appliedADocumentIssue_1", "УВД");
    context.setVariable("agentLocationLevel2Type", null);
    context.setVariable("agentLocationLevel3Value", "");
    context.setVariable("declLocationLocationOther", "");
    context.setVariable("declLocationLocationApartmentType", "кв");
    context.setVariable("paymentDate_1", new Date());
    context.setVariable("declPersonPDocumentSeries", "1222");
    context.setVariable("declLocationLocationLevel2Type", null);
    context.setVariable("cadastralPassportStreetName", "Южная");
    context.setVariable("declPersonPDocumentIssueOrgan", "УВД");
    context.setVariable("agentDCity", "г");
    context.setVariable("paymentSum_1", "10000");
    context.setVariable("agentLocationLevel1Value", "1");
    context.setVariable("agentLocationOther", "");
    context.setVariable("cadastralPassportLocationLevel1Value", "1");
    context.setVariable("agentPhone", "123121");
    context.setVariable("agentUrbanDistictType", null);
    context.setVariable("declLocationDistrictType", null);
    context.setVariable("agentFIOFirst", "Антон");
    context.setVariable("agentLocalityName", "");
    context.setVariable("declPersonPhone", "12212212221");
    context.setVariable("payment", "1");
    context.setVariable("agentLocalityType", null);
    context.setVariable("smevTest", "Первичный запрос");
    context.setVariable("declLocationSovietVillageType", null);
    context.setVariable("agentSNILS", "112-233-332 33");
    context.setVariable("declLocationLocationLevel2Value", "");
    context.setVariable("Individuals", "Индивидуальные предпринематели");
    context.setVariable("declPersonMarriageStatus", "женат");
    context.setVariable("procedureTypeName", "0");
    context.setVariable("agentPDocumentSeries", "1221");
    context.setVariable("agentDStreets", "ул");
    context.setVariable("cadastralPassportLocationApartmentType", "кв");
    context.setVariable("declKind", "357007000000");
    context.setVariable("declLocationLocationLevel3Value", "");
    context.setVariable("declGovernancePhone", "12342323");
    context.setVariable("enclosure_request_type", "CADASTRAL_PASSPORT");
    context.setVariable("paymentFIOPayer_1", "ФИО плательщика");
    context.setVariable("agentCLADR", "");
    context.setVariable("agentPDocumentDate", new Date());
    context.setVariable("declLocationUrbanDistictType", null);
    context.setVariable("agentLocationLevel3Type", null);
    context.setVariable("appliedADocumentOriginalQuantity_1", "1");
    context.setVariable("declLegalPersonEmail", "tesst@rerer.com");
    context.setVariable("agentPostalCode", "");
    context.setVariable("cadastralPassportSovietVillageName", "");
    context.setVariable("declLegalPersonINN", "12343434");
    context.setVariable("smevInitialRegNumber", "137561929017082693");
    context.setVariable("declPersonPDocumentCode", "008001001000");
    context.setVariable("declPersonPDocumentNumber", "121212");
    context.setVariable("cadastralPassportDStreets", "ул");
    context.setVariable("paymentOKATO_1", null);
    context.setVariable("agentUrbanDistictName", "");
    context.setVariable("declLocationLocationNote", "");
    context.setVariable("paymentSettlement_Account_1", "1234345546565565");
    context.setVariable("cadastralPassportLocationNote", "");
    context.setVariable("appliedADocumentCode_1", "008001001000");
    //context.setVariable("declGovernanceContactInfo", "");
    context.setVariable("paymentBank_Name_1", "Сбербанк");
    context.setVariable("agentLocationApartmentValue", "1");
    context.setVariable("declLocationOKATO", null);
    context.setVariable("declLocationLocationApartmentValue", "1");
    context.setVariable("declLocationDistrictName", "");
    context.setVariable("declLocationDStreets", "ул");
    context.setVariable("cadastralPassportLocationLevel2Type", null);
    context.setVariable("declGovernanceCode", "007001001001");
    context.setVariable("cadastralPassportDCity", "г");
    context.setVariable("cadastralPassportLocalityName", "");
    context.setVariable("agentLocationLevel1Type", "д");
    context.setVariable("cadastralPassportDistrictName", "");
    context.setVariable("agentFIOPatronymic", "Антонович");
    context.setVariable("agentDistrictName", "");
    context.setVariable("cadastralPassportLocationLevel1Type", "д");
    context.setVariable("declGovernanceName", "Пенсионный фонд");
    context.setVariable("serviceId", "3");
    context.setVariable("declPersonPDocumentDate", null);
    context.setVariable("declLocationStreetName", "Южная");
    context.setVariable("appliedADocumentDate_1", new Date());
    context.setVariable("declarantLogin", "test");
    context.setVariable("cadastralPassportLocationLevel3Type", null);
    context.setVariable("declLocationRegion", "40");
    context.setVariable("agentPDocumentCode", "008001001000");
    context.setVariable("declLocationSovietVillageName", "");
    context.setVariable("declLocationLocationLevel1Type", "д");
    context.setVariable("oktmo", "01234567");
    context.setVariable("declLegalPersonName", "Точка");
    context.setVariable("declLegalPersonOGRN", "1212122");
    context.setVariable("paymentNumber_1", "1");
    context.setVariable("cadastralPassportLocalityType", null);
    context.setVariable("cadastralPassportUrbanDistictType", null);
    context.setVariable("declLocationPostalCode", "");
    context.setVariable("agentEmail", "reeer@erere.com");
    context.setVariable("agentPDocumentNumber", "121212");
    context.setVariable("agentPDocumentIssueOrgan", "УВД");
    context.setVariable("declarantType", "GOVERNANCE");
    context.setVariable("appliedADocumentDesc_1", "нет");
    context.setVariable("agentOKATO", null);
    context.setVariable("paymentBIC_1", "123456675");
    context.setVariable("agentFIOSurname", "Антонов");
    context.setVariable("agentSovietVillageType", null);
    context.setVariable("declLocationLocalityName", "");
    context.setVariable("agentDistrictType", null);
    context.setVariable("requestType", "558103080000");
    context.setVariable("declLocationCLADR", "");
    context.setVariable("agentLocationNote", "");
    context.setVariable("Physical", "Физические лица");
    context.setVariable("agentKind", "356002000000");
    context.setVariable("agentLocationApartmentType", "кв");
    context.setVariable("declLocationCityName", "Калуга");
    context.setVariable("appliedADocumentOriginalQuantitySheet_1", "1");
    context.setVariable("applied", "1");
    context.setVariable("appliedADocumentName_1", "Паспорт гражданина РФ");
    context.setVariable("declLocationLocationLevel3Type", null);
    context.setVariable("declPersonFIOSurname", "Иванов");
    context.setVariable("declPersonFIOPatronymic", "Иванович");
  }
}
