//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.01 at 01:34:16 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://fss.ru/SvedNoRegDobrStrahNoTrudOrMat")
package ru.fss.svednoregdobrstrahnotrudormat;
