//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.01 at 01:34:16 PM MSK 
//


package ru.fss.svednoregdobrstrahnotrudormat;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ответ complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ответ">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="iNameCiv" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fNameCiv" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mNameCiv" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="codeKind" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="seriesNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="docDataCiv" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="inn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="snils" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="regionTo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nameOrganizationTo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="obtainingGrants2" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="registrationNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="registrationDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="removalAccountDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u043e\u0442\u0432\u0435\u0442")
public class Ответ {

    @XmlAttribute(name = "iNameCiv", required = true)
    protected String iNameCiv;
    @XmlAttribute(name = "fNameCiv", required = true)
    protected String fNameCiv;
    @XmlAttribute(name = "mNameCiv")
    protected String mNameCiv;
    @XmlAttribute(name = "codeKind", required = true)
    protected String codeKind;
    @XmlAttribute(name = "seriesNumber", required = true)
    protected String seriesNumber;
    @XmlAttribute(name = "docDataCiv", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar docDataCiv;
    @XmlAttribute(name = "inn")
    protected String inn;
    @XmlAttribute(name = "snils")
    protected String snils;
    @XmlAttribute(name = "regionTo", required = true)
    protected String regionTo;
    @XmlAttribute(name = "nameOrganizationTo", required = true)
    protected String nameOrganizationTo;
    @XmlAttribute(name = "obtainingGrants2", required = true)
    protected boolean obtainingGrants2;
    @XmlAttribute(name = "registrationNumber", required = true)
    protected String registrationNumber;
    @XmlAttribute(name = "registrationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar registrationDate;
    @XmlAttribute(name = "removalAccountDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar removalAccountDate;

    /**
     * Gets the value of the iNameCiv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINameCiv() {
        return iNameCiv;
    }

    /**
     * Sets the value of the iNameCiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINameCiv(String value) {
        this.iNameCiv = value;
    }

    /**
     * Gets the value of the fNameCiv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFNameCiv() {
        return fNameCiv;
    }

    /**
     * Sets the value of the fNameCiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFNameCiv(String value) {
        this.fNameCiv = value;
    }

    /**
     * Gets the value of the mNameCiv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMNameCiv() {
        return mNameCiv;
    }

    /**
     * Sets the value of the mNameCiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMNameCiv(String value) {
        this.mNameCiv = value;
    }

    /**
     * Gets the value of the codeKind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeKind() {
        return codeKind;
    }

    /**
     * Sets the value of the codeKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeKind(String value) {
        this.codeKind = value;
    }

    /**
     * Gets the value of the seriesNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeriesNumber() {
        return seriesNumber;
    }

    /**
     * Sets the value of the seriesNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeriesNumber(String value) {
        this.seriesNumber = value;
    }

    /**
     * Gets the value of the docDataCiv property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDocDataCiv() {
        return docDataCiv;
    }

    /**
     * Sets the value of the docDataCiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDocDataCiv(XMLGregorianCalendar value) {
        this.docDataCiv = value;
    }

    /**
     * Gets the value of the inn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInn() {
        return inn;
    }

    /**
     * Sets the value of the inn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInn(String value) {
        this.inn = value;
    }

    /**
     * Gets the value of the snils property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSnils() {
        return snils;
    }

    /**
     * Sets the value of the snils property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSnils(String value) {
        this.snils = value;
    }

    /**
     * Gets the value of the regionTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegionTo() {
        return regionTo;
    }

    /**
     * Sets the value of the regionTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegionTo(String value) {
        this.regionTo = value;
    }

    /**
     * Gets the value of the nameOrganizationTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameOrganizationTo() {
        return nameOrganizationTo;
    }

    /**
     * Sets the value of the nameOrganizationTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameOrganizationTo(String value) {
        this.nameOrganizationTo = value;
    }

    /**
     * Gets the value of the obtainingGrants2 property.
     * 
     */
    public boolean isObtainingGrants2() {
        return obtainingGrants2;
    }

    /**
     * Sets the value of the obtainingGrants2 property.
     * 
     */
    public void setObtainingGrants2(boolean value) {
        this.obtainingGrants2 = value;
    }

    /**
     * Gets the value of the registrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationNumber() {
        return registrationNumber;
    }

    /**
     * Sets the value of the registrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationNumber(String value) {
        this.registrationNumber = value;
    }

    /**
     * Gets the value of the registrationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRegistrationDate() {
        return registrationDate;
    }

    /**
     * Sets the value of the registrationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRegistrationDate(XMLGregorianCalendar value) {
        this.registrationDate = value;
    }

    /**
     * Gets the value of the removalAccountDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRemovalAccountDate() {
        return removalAccountDate;
    }

    /**
     * Sets the value of the removalAccountDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRemovalAccountDate(XMLGregorianCalendar value) {
        this.removalAccountDate = value;
    }

}
