//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.10 at 10:59:29 AM MSK 
//


package unisoft.ws.egrnxx.responseksul;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the unisoft.ws.egrnxx.responseksul package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: unisoft.ws.egrnxx.responseksul
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Документ }
     * 
     */
    public Документ createДокумент() {
        return new Документ();
    }

    /**
     * Create an instance of {@link АдрРФТипВып }
     * 
     */
    public АдрРФТипВып createАдрРФТипВып() {
        return new АдрРФТипВып();
    }

    /**
     * Create an instance of {@link Документ.Ответ }
     * 
     */
    public Документ.Ответ createДокументОтвет() {
        return new Документ.Ответ();
    }

    /**
     * Create an instance of {@link Документ.Ответ.СвЮЛ }
     * 
     */
    public Документ.Ответ.СвЮЛ createДокументОтветСвЮЛ() {
        return new Документ.Ответ.СвЮЛ();
    }

    /**
     * Create an instance of {@link Документ.Ответ.СвЮЛ.СвУчетНО }
     * 
     */
    public Документ.Ответ.СвЮЛ.СвУчетНО createДокументОтветСвЮЛСвУчетНО() {
        return new Документ.Ответ.СвЮЛ.СвУчетНО();
    }

    /**
     * Create an instance of {@link Документ.Ответ.СвЮЛ.СвУправлДеят }
     * 
     */
    public Документ.Ответ.СвЮЛ.СвУправлДеят createДокументОтветСвЮЛСвУправлДеят() {
        return new Документ.Ответ.СвЮЛ.СвУправлДеят();
    }

    /**
     * Create an instance of {@link ФИОТип }
     * 
     */
    public ФИОТип createФИОТип() {
        return new ФИОТип();
    }

    /**
     * Create an instance of {@link АдрРФТипВып.Регион }
     * 
     */
    public АдрРФТипВып.Регион createАдрРФТипВыпРегион() {
        return new АдрРФТипВып.Регион();
    }

    /**
     * Create an instance of {@link АдрРФТипВып.Район }
     * 
     */
    public АдрРФТипВып.Район createАдрРФТипВыпРайон() {
        return new АдрРФТипВып.Район();
    }

    /**
     * Create an instance of {@link АдрРФТипВып.Город }
     * 
     */
    public АдрРФТипВып.Город createАдрРФТипВыпГород() {
        return new АдрРФТипВып.Город();
    }

    /**
     * Create an instance of {@link АдрРФТипВып.НаселПункт }
     * 
     */
    public АдрРФТипВып.НаселПункт createАдрРФТипВыпНаселПункт() {
        return new АдрРФТипВып.НаселПункт();
    }

    /**
     * Create an instance of {@link АдрРФТипВып.Улица }
     * 
     */
    public АдрРФТипВып.Улица createАдрРФТипВыпУлица() {
        return new АдрРФТипВып.Улица();
    }

    /**
     * Create an instance of {@link Документ.Ответ.СвЮЛ.СвСтатус }
     * 
     */
    public Документ.Ответ.СвЮЛ.СвСтатус createДокументОтветСвЮЛСвСтатус() {
        return new Документ.Ответ.СвЮЛ.СвСтатус();
    }

    /**
     * Create an instance of {@link Документ.Ответ.СвЮЛ.СвРегОрг }
     * 
     */
    public Документ.Ответ.СвЮЛ.СвРегОрг createДокументОтветСвЮЛСвРегОрг() {
        return new Документ.Ответ.СвЮЛ.СвРегОрг();
    }

    /**
     * Create an instance of {@link Документ.Ответ.СвЮЛ.СвУчетНО.СвНО }
     * 
     */
    public Документ.Ответ.СвЮЛ.СвУчетНО.СвНО createДокументОтветСвЮЛСвУчетНОСвНО() {
        return new Документ.Ответ.СвЮЛ.СвУчетНО.СвНО();
    }

    /**
     * Create an instance of {@link Документ.Ответ.СвЮЛ.СвУправлДеят.СведДолжнФЛ }
     * 
     */
    public Документ.Ответ.СвЮЛ.СвУправлДеят.СведДолжнФЛ createДокументОтветСвЮЛСвУправлДеятСведДолжнФЛ() {
        return new Документ.Ответ.СвЮЛ.СвУправлДеят.СведДолжнФЛ();
    }

    /**
     * Create an instance of {@link Документ.Ответ.СвЮЛ.СвУправлДеят.УпрОргРос }
     * 
     */
    public Документ.Ответ.СвЮЛ.СвУправлДеят.УпрОргРос createДокументОтветСвЮЛСвУправлДеятУпрОргРос() {
        return new Документ.Ответ.СвЮЛ.СвУправлДеят.УпрОргРос();
    }

    /**
     * Create an instance of {@link Документ.Ответ.СвЮЛ.СвУправлДеят.УпрОргИн }
     * 
     */
    public Документ.Ответ.СвЮЛ.СвУправлДеят.УпрОргИн createДокументОтветСвЮЛСвУправлДеятУпрОргИн() {
        return new Документ.Ответ.СвЮЛ.СвУправлДеят.УпрОргИн();
    }

}
