
package ru.codeinside.esia;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConnectESIAService", targetNamespace = "http://oep-penza.ru/com/oep/esia", wsdlLocation = "file:/home/kirill/help/wsdl/connectesia.wsdl")
public class ConnectESIAService
    extends Service
{

    private final static URL CONNECTESIASERVICE_WSDL_LOCATION;
    private final static WebServiceException CONNECTESIASERVICE_EXCEPTION;
    private final static QName CONNECTESIASERVICE_QNAME = new QName("http://oep-penza.ru/com/oep/esia", "ConnectESIAService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/kirill/help/wsdl/connectesia.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONNECTESIASERVICE_WSDL_LOCATION = url;
        CONNECTESIASERVICE_EXCEPTION = e;
    }

    public ConnectESIAService() {
        super(__getWsdlLocation(), CONNECTESIASERVICE_QNAME);
    }

    public ConnectESIAService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONNECTESIASERVICE_QNAME, features);
    }

    public ConnectESIAService(URL wsdlLocation) {
        super(wsdlLocation, CONNECTESIASERVICE_QNAME);
    }

    public ConnectESIAService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONNECTESIASERVICE_QNAME, features);
    }

    public ConnectESIAService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConnectESIAService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConnectESIA
     */
    @WebEndpoint(name = "ConnectESIAPort")
    public ConnectESIA getConnectESIAPort() {
        return super.getPort(new QName("http://oep-penza.ru/com/oep/esia", "ConnectESIAPort"), ConnectESIA.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConnectESIA
     */
    @WebEndpoint(name = "ConnectESIAPort")
    public ConnectESIA getConnectESIAPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://oep-penza.ru/com/oep/esia", "ConnectESIAPort"), ConnectESIA.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONNECTESIASERVICE_EXCEPTION!= null) {
            throw CONNECTESIASERVICE_EXCEPTION;
        }
        return CONNECTESIASERVICE_WSDL_LOCATION;
    }

}
