//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.16 at 03:46:51 PM CET 
//


package org.ow2.easywsdl.wsdl.org.w3.ns.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.ow2.easywsdl.u.builder.EqualsBuilder;
import org.ow2.easywsdl.u.builder.HashCodeBuilder;
import org.ow2.easywsdl.u.builder.ToStringBuilder;
import org.jvnet.jaxb2_commons.lang.CopyTo;
import org.jvnet.jaxb2_commons.lang.Copyable;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.builder.CopyBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBCopyBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBToStringBuilder;
import org.w3c.dom.Element;


/**
 * 
 *         Although correct, this type declaration does not capture
 *         all the constraints on the contents of the wsdl:description
 *         element as defined by the WSDL 2.0 specification.
 * 
 *         In particular, the ordering constraints wrt elements preceding
 *         and following the wsdl:types child element are not captured, as
 *         attempts to incorporate such restrictions in the schema
 *         ran afoul of the UPA (Unique Particle Attribution) rule
 *         in the XML Schema language.
 * 
 *         Please refer to the WSDL 2.0 specification for
 * 	additional information on the contents of this type.
 *       
 * 
 * <p>Java class for DescriptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DescriptionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.w3.org/ns/wsdl}ExtensibleDocumentedType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://www.w3.org/ns/wsdl}import"/>
 *         &lt;element ref="{http://www.w3.org/ns/wsdl}include"/>
 *         &lt;element ref="{http://www.w3.org/ns/wsdl}types"/>
 *         &lt;element ref="{http://www.w3.org/ns/wsdl}interface"/>
 *         &lt;element ref="{http://www.w3.org/ns/wsdl}binding"/>
 *         &lt;element ref="{http://www.w3.org/ns/wsdl}service"/>
 *         &lt;any processContents='lax' namespace='##other'/>
 *       &lt;/choice>
 *       &lt;attribute name="targetNamespace" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescriptionType", propOrder = {
    "importOrIncludeOrTypes"
})
public class DescriptionType
    extends ExtensibleDocumentedType
    implements CopyTo, Copyable, Equals, HashCode, ToString
{

    @XmlElementRefs({
        @XmlElementRef(name = "import", namespace = "http://www.w3.org/ns/wsdl", type = JAXBElement.class),
        @XmlElementRef(name = "binding", namespace = "http://www.w3.org/ns/wsdl", type = JAXBElement.class),
        @XmlElementRef(name = "service", namespace = "http://www.w3.org/ns/wsdl", type = JAXBElement.class),
        @XmlElementRef(name = "include", namespace = "http://www.w3.org/ns/wsdl", type = JAXBElement.class),
        @XmlElementRef(name = "types", namespace = "http://www.w3.org/ns/wsdl", type = JAXBElement.class),
        @XmlElementRef(name = "interface", namespace = "http://www.w3.org/ns/wsdl", type = JAXBElement.class)
    })
    @XmlAnyElement(lax = true)
    protected List<Object> importOrIncludeOrTypes;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String targetNamespace;

    /**
     * Gets the value of the importOrIncludeOrTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the importOrIncludeOrTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImportOrIncludeOrTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ImportType }{@code >}
     * {@link Element }
     * {@link JAXBElement }{@code <}{@link BindingType }{@code >}
     * {@link JAXBElement }{@code <}{@link ServiceType }{@code >}
     * {@link JAXBElement }{@code <}{@link IncludeType }{@code >}
     * {@link Object }
     * {@link JAXBElement }{@code <}{@link TypesType }{@code >}
     * {@link JAXBElement }{@code <}{@link InterfaceType }{@code >}
     * 
     * 
     */
    public List<Object> getImportOrIncludeOrTypes() {
        if (importOrIncludeOrTypes == null) {
            importOrIncludeOrTypes = new ArrayList<Object>();
        }
        return this.importOrIncludeOrTypes;
    }

    /**
     * Gets the value of the targetNamespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetNamespace() {
        return targetNamespace;
    }

    /**
     * Sets the value of the targetNamespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetNamespace(String value) {
        this.targetNamespace = value;
    }

    public void toString(ToStringBuilder toStringBuilder) {
        super.toString(toStringBuilder);
        {
            List<Object> theImportOrIncludeOrTypes;
            theImportOrIncludeOrTypes = this.getImportOrIncludeOrTypes();
            toStringBuilder.append("importOrIncludeOrTypes", theImportOrIncludeOrTypes);
        }
        {
            String theTargetNamespace;
            theTargetNamespace = this.getTargetNamespace();
            toStringBuilder.append("targetNamespace", theTargetNamespace);
        }
    }

    public String toString() {
        final ToStringBuilder toStringBuilder = new JAXBToStringBuilder(this);
        toString(toStringBuilder);
        return toStringBuilder.toString();
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof DescriptionType)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        super.equals(object, equalsBuilder);
        final DescriptionType that = ((DescriptionType) object);
        equalsBuilder.append(this.getImportOrIncludeOrTypes(), that.getImportOrIncludeOrTypes());
        equalsBuilder.append(this.getTargetNamespace(), that.getTargetNamespace());
    }

    public boolean equals(Object object) {
        if (!(object instanceof DescriptionType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        super.hashCode(hashCodeBuilder);
        hashCodeBuilder.append(this.getImportOrIncludeOrTypes());
        hashCodeBuilder.append(this.getTargetNamespace());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

    public Object copyTo(Object target, CopyBuilder copyBuilder) {
        final DescriptionType copy = ((target == null)?((DescriptionType) createCopy()):((DescriptionType) target));
        super.copyTo(copy, copyBuilder);
        {
            List<Object> sourceImportOrIncludeOrTypes;
            sourceImportOrIncludeOrTypes = this.getImportOrIncludeOrTypes();
            List<Object> copyImportOrIncludeOrTypes = ((List<Object> ) copyBuilder.copy(sourceImportOrIncludeOrTypes));
            copy.importOrIncludeOrTypes = null;
            List<Object> uniqueImportOrIncludeOrTypesl = copy.getImportOrIncludeOrTypes();
            uniqueImportOrIncludeOrTypesl.addAll(copyImportOrIncludeOrTypes);
        }
        {
            String sourceTargetNamespace;
            sourceTargetNamespace = this.getTargetNamespace();
            String copyTargetNamespace = ((String) copyBuilder.copy(sourceTargetNamespace));
            copy.setTargetNamespace(copyTargetNamespace);
        }
        return copy;
    }

    public Object copyTo(Object target) {
        final CopyBuilder copyBuilder = new JAXBCopyBuilder();
        return copyTo(target, copyBuilder);
    }

    public Object createCopy() {
        return new DescriptionType();
    }

}
