//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.14 at 12:23:19 PM MSK 
//


package ru.gosuslugi.smev.rev111111;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ru.kdmid.SmevreqAppData;
import ru.kdmid.SmevresAppData;


/**
 * <p>Java class for smevAppData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="smevAppData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.kdmid.ru/}Request" minOccurs="0"/>
 *         &lt;element ref="{http://www.kdmid.ru/}Response" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "smevAppData", propOrder = {
    "request",
    "response"
})
public class SmevAppData {

    @XmlElement(name = "Request", namespace = "http://www.kdmid.ru/")
    protected SmevreqAppData request;
    @XmlElement(name = "Response", namespace = "http://www.kdmid.ru/")
    protected SmevresAppData response;

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link SmevreqAppData }
     *     
     */
    public SmevreqAppData getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmevreqAppData }
     *     
     */
    public void setRequest(SmevreqAppData value) {
        this.request = value;
    }

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link SmevresAppData }
     *     
     */
    public SmevresAppData getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmevresAppData }
     *     
     */
    public void setResponse(SmevresAppData value) {
        this.response = value;
    }

}
