//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 12:01:56 PM MSK 
//


package biz.red_soft.ncore.dx._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DXDocumentResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DXDocumentResult">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.red-soft.biz/ncore/dx/1.1}DXBlock">
 *       &lt;sequence>
 *         &lt;element name="Status" type="{http://www.red-soft.biz/ncore/dx/1.1}ProcessResult"/>
 *         &lt;element name="DocRef" type="{http://www.red-soft.biz/ncore/dx/1.1}DocumentRef"/>
 *         &lt;element name="State" type="{http://www.red-soft.biz/ncore/dx/1.1}DocumentState"/>
 *         &lt;choice>
 *           &lt;element name="ErrorMessage" type="{http://www.red-soft.biz/ncore/dx/1.1}MessageEx"/>
 *           &lt;sequence>
 *             &lt;element name="DocDate" type="{http://www.red-soft.biz/ncore/dx/1.1}Date"/>
 *             &lt;element name="DocNumber" type="{http://www.red-soft.biz/ncore/dx/1.1}DocumentNumber"/>
 *             &lt;element name="Document" type="{http://www.red-soft.biz/ncore/dx/1.1}DocumentContainer"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DXDocumentResult", propOrder = {
    "status",
    "docRef",
    "state",
    "errorMessage",
    "docDate",
    "docNumber",
    "document"
})
public class DXDocumentResult
    extends DXBlock
{

    @XmlElement(name = "Status", required = true)
    protected ProcessResult status;
    @XmlElement(name = "DocRef", required = true)
    protected DocumentRef docRef;
    @XmlElement(name = "State", required = true)
    protected String state;
    @XmlElement(name = "ErrorMessage")
    protected MessageEx errorMessage;
    @XmlElement(name = "DocDate")
    protected XMLGregorianCalendar docDate;
    @XmlElement(name = "DocNumber")
    protected String docNumber;
    @XmlElement(name = "Document")
    protected DocumentContainer document;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessResult }
     *     
     */
    public ProcessResult getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessResult }
     *     
     */
    public void setStatus(ProcessResult value) {
        this.status = value;
    }

    /**
     * Gets the value of the docRef property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentRef }
     *     
     */
    public DocumentRef getDocRef() {
        return docRef;
    }

    /**
     * Sets the value of the docRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentRef }
     *     
     */
    public void setDocRef(DocumentRef value) {
        this.docRef = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the errorMessage property.
     * 
     * @return
     *     possible object is
     *     {@link MessageEx }
     *     
     */
    public MessageEx getErrorMessage() {
        return errorMessage;
    }

    /**
     * Sets the value of the errorMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageEx }
     *     
     */
    public void setErrorMessage(MessageEx value) {
        this.errorMessage = value;
    }

    /**
     * Gets the value of the docDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDocDate() {
        return docDate;
    }

    /**
     * Sets the value of the docDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDocDate(XMLGregorianCalendar value) {
        this.docDate = value;
    }

    /**
     * Gets the value of the docNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocNumber() {
        return docNumber;
    }

    /**
     * Sets the value of the docNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocNumber(String value) {
        this.docNumber = value;
    }

    /**
     * Gets the value of the document property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentContainer }
     *     
     */
    public DocumentContainer getDocument() {
        return document;
    }

    /**
     * Sets the value of the document property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentContainer }
     *     
     */
    public void setDocument(DocumentContainer value) {
        this.document = value;
    }

}
