//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 12:01:56 PM MSK 
//


package biz.red_soft.ncore.dx._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DXFileData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DXFileData">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.red-soft.biz/ncore/dx/1.1}DXBlock">
 *       &lt;sequence>
 *         &lt;element name="Data" type="{http://www.red-soft.biz/ncore/dx/1.1}FileDataBlock"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DXFileData", propOrder = {
    "data"
})
public class DXFileData
    extends DXBlock
{

    @XmlElement(name = "Data", required = true)
    protected FileDataBlock data;

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link FileDataBlock }
     *     
     */
    public FileDataBlock getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileDataBlock }
     *     
     */
    public void setData(FileDataBlock value) {
        this.data = value;
    }

}
