//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 12:01:56 PM MSK 
//


package biz.red_soft.schemas.fssp.common._2011._0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Результат автоматической обработки документов
 * 
 * <p>Java class for AutoProcessRs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AutoProcessRs">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}SyncRs">
 *       &lt;choice>
 *         &lt;element name="ipDataInfo" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}IPDataInfo"/>
 *         &lt;element name="debtorIPListResponse" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}DebtorIPListResponseType"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AutoProcessRs", propOrder = {
    "ipDataInfo",
    "debtorIPListResponse"
})
public class AutoProcessRs
    extends SyncRs
{

    protected IPDataInfo ipDataInfo;
    protected DebtorIPListResponseType debtorIPListResponse;

    /**
     * Gets the value of the ipDataInfo property.
     * 
     * @return
     *     possible object is
     *     {@link IPDataInfo }
     *     
     */
    public IPDataInfo getIpDataInfo() {
        return ipDataInfo;
    }

    /**
     * Sets the value of the ipDataInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPDataInfo }
     *     
     */
    public void setIpDataInfo(IPDataInfo value) {
        this.ipDataInfo = value;
    }

    /**
     * Gets the value of the debtorIPListResponse property.
     * 
     * @return
     *     possible object is
     *     {@link DebtorIPListResponseType }
     *     
     */
    public DebtorIPListResponseType getDebtorIPListResponse() {
        return debtorIPListResponse;
    }

    /**
     * Sets the value of the debtorIPListResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link DebtorIPListResponseType }
     *     
     */
    public void setDebtorIPListResponse(DebtorIPListResponseType value) {
        this.debtorIPListResponse = value;
    }

}
