//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 12:01:56 PM MSK 
//


package biz.red_soft.schemas.fssp.common._2011._0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Автоматическая обработка документов
 * 
 * <p>Java class for AutoProcessRq complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AutoProcessRq">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}SyncRq">
 *       &lt;choice>
 *         &lt;element name="ipDataRequest" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}IPDataRequest"/>
 *         &lt;element name="debtorIPListRequest" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}DebtorIPListRequestType"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AutoProcessRq", propOrder = {
    "ipDataRequest",
    "debtorIPListRequest"
})
public class AutoProcessRq
    extends SyncRq
{

    protected IPDataRequest ipDataRequest;
    protected DebtorIPListRequestType debtorIPListRequest;

    /**
     * Gets the value of the ipDataRequest property.
     * 
     * @return
     *     possible object is
     *     {@link IPDataRequest }
     *     
     */
    public IPDataRequest getIpDataRequest() {
        return ipDataRequest;
    }

    /**
     * Sets the value of the ipDataRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPDataRequest }
     *     
     */
    public void setIpDataRequest(IPDataRequest value) {
        this.ipDataRequest = value;
    }

    /**
     * Gets the value of the debtorIPListRequest property.
     * 
     * @return
     *     possible object is
     *     {@link DebtorIPListRequestType }
     *     
     */
    public DebtorIPListRequestType getDebtorIPListRequest() {
        return debtorIPListRequest;
    }

    /**
     * Sets the value of the debtorIPListRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link DebtorIPListRequestType }
     *     
     */
    public void setDebtorIPListRequest(DebtorIPListRequestType value) {
        this.debtorIPListRequest = value;
    }

}
