//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 12:01:56 PM MSK 
//


package biz.red_soft.schemas.fssp.common._2011._0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Тип сведений AvailabilityAccDepoDataType "Наличие счетов ДЕПО"
 * 
 * <p>Java class for AvailabilityAccDepoDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AvailabilityAccDepoDataType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}InformationType">
 *       &lt;sequence>
 *         &lt;element name="StrAcc" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}String_1_20"/>
 *         &lt;element name="DeptCode" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}String_1_10" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AvailabilityAccDepoDataType", propOrder = {
    "strAcc",
    "deptCode"
})
public class AvailabilityAccDepoDataType
    extends InformationType
{

    @XmlElement(name = "StrAcc", required = true)
    protected String strAcc;
    @XmlElement(name = "DeptCode")
    protected String deptCode;

    /**
     * Gets the value of the strAcc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrAcc() {
        return strAcc;
    }

    /**
     * Sets the value of the strAcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrAcc(String value) {
        this.strAcc = value;
    }

    /**
     * Gets the value of the deptCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * Sets the value of the deptCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeptCode(String value) {
        this.deptCode = value;
    }

}
