//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 12:01:56 PM MSK 
//


package biz.red_soft.schemas.fssp.common._2011._0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.w3._2000._09.xmldsig.SignatureType;


/**
 * Запрос в ВУЦ
 * 
 * <p>Java class for CaRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CaRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="internalKey" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}InternalKeyType"/>
 *         &lt;element name="docNumber" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}DocNumberType"/>
 *         &lt;element name="docDate" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}Date"/>
 *         &lt;element name="spiKey" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}InternalKeyType"/>
 *         &lt;element name="spiPost" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}PostType"/>
 *         &lt;element name="spiFIO" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}FioType"/>
 *         &lt;element name="chiefSpiKey" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}InternalKeyType"/>
 *         &lt;element name="chiefSpiPost" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}PostType"/>
 *         &lt;element name="chiefSpiFIO" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}FioType"/>
 *         &lt;element name="requestType" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}VucRequestType"/>
 *         &lt;element name="certRequest" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}String_1_4000"/>
 *         &lt;element name="certSign" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}String_1_4000" minOccurs="0"/>
 *         &lt;element name="SignDateTime" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}DateTime" minOccurs="0"/>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CaRequest", propOrder = {
    "internalKey",
    "docNumber",
    "docDate",
    "spiKey",
    "spiPost",
    "spiFIO",
    "chiefSpiKey",
    "chiefSpiPost",
    "chiefSpiFIO",
    "requestType",
    "certRequest",
    "certSign",
    "signDateTime",
    "signature"
})
public class CaRequest {

    protected long internalKey;
    @XmlElement(required = true)
    protected String docNumber;
    @XmlElement(required = true)
    protected XMLGregorianCalendar docDate;
    protected long spiKey;
    @XmlElement(required = true)
    protected String spiPost;
    @XmlElement(required = true)
    protected FioType spiFIO;
    protected long chiefSpiKey;
    @XmlElement(required = true)
    protected String chiefSpiPost;
    @XmlElement(required = true)
    protected FioType chiefSpiFIO;
    @XmlElement(required = true)
    protected String requestType;
    @XmlElement(required = true)
    protected String certRequest;
    protected String certSign;
    @XmlElement(name = "SignDateTime")
    protected XMLGregorianCalendar signDateTime;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#")
    protected List<SignatureType> signature;

    /**
     * Gets the value of the internalKey property.
     * 
     */
    public long getInternalKey() {
        return internalKey;
    }

    /**
     * Sets the value of the internalKey property.
     * 
     */
    public void setInternalKey(long value) {
        this.internalKey = value;
    }

    /**
     * Gets the value of the docNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocNumber() {
        return docNumber;
    }

    /**
     * Sets the value of the docNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocNumber(String value) {
        this.docNumber = value;
    }

    /**
     * Gets the value of the docDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDocDate() {
        return docDate;
    }

    /**
     * Sets the value of the docDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDocDate(XMLGregorianCalendar value) {
        this.docDate = value;
    }

    /**
     * Gets the value of the spiKey property.
     * 
     */
    public long getSpiKey() {
        return spiKey;
    }

    /**
     * Sets the value of the spiKey property.
     * 
     */
    public void setSpiKey(long value) {
        this.spiKey = value;
    }

    /**
     * Gets the value of the spiPost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpiPost() {
        return spiPost;
    }

    /**
     * Sets the value of the spiPost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpiPost(String value) {
        this.spiPost = value;
    }

    /**
     * Gets the value of the spiFIO property.
     * 
     * @return
     *     possible object is
     *     {@link FioType }
     *     
     */
    public FioType getSpiFIO() {
        return spiFIO;
    }

    /**
     * Sets the value of the spiFIO property.
     * 
     * @param value
     *     allowed object is
     *     {@link FioType }
     *     
     */
    public void setSpiFIO(FioType value) {
        this.spiFIO = value;
    }

    /**
     * Gets the value of the chiefSpiKey property.
     * 
     */
    public long getChiefSpiKey() {
        return chiefSpiKey;
    }

    /**
     * Sets the value of the chiefSpiKey property.
     * 
     */
    public void setChiefSpiKey(long value) {
        this.chiefSpiKey = value;
    }

    /**
     * Gets the value of the chiefSpiPost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChiefSpiPost() {
        return chiefSpiPost;
    }

    /**
     * Sets the value of the chiefSpiPost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChiefSpiPost(String value) {
        this.chiefSpiPost = value;
    }

    /**
     * Gets the value of the chiefSpiFIO property.
     * 
     * @return
     *     possible object is
     *     {@link FioType }
     *     
     */
    public FioType getChiefSpiFIO() {
        return chiefSpiFIO;
    }

    /**
     * Sets the value of the chiefSpiFIO property.
     * 
     * @param value
     *     allowed object is
     *     {@link FioType }
     *     
     */
    public void setChiefSpiFIO(FioType value) {
        this.chiefSpiFIO = value;
    }

    /**
     * Gets the value of the requestType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestType() {
        return requestType;
    }

    /**
     * Sets the value of the requestType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestType(String value) {
        this.requestType = value;
    }

    /**
     * Gets the value of the certRequest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertRequest() {
        return certRequest;
    }

    /**
     * Sets the value of the certRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertRequest(String value) {
        this.certRequest = value;
    }

    /**
     * Gets the value of the certSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertSign() {
        return certSign;
    }

    /**
     * Sets the value of the certSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertSign(String value) {
        this.certSign = value;
    }

    /**
     * Gets the value of the signDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSignDateTime() {
        return signDateTime;
    }

    /**
     * Sets the value of the signDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSignDateTime(XMLGregorianCalendar value) {
        this.signDateTime = value;
    }

    /**
     * ЭП Gets the value of the signature property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the signature property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSignature().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SignatureType }
     * 
     * 
     */
    public List<SignatureType> getSignature() {
        if (signature == null) {
            signature = new ArrayList<SignatureType>();
        }
        return this.signature;
    }

}
