//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 12:01:56 PM MSK 
//


package biz.red_soft.schemas.fssp.common._2011._0;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Адрес юридического лица
 * 
 * <p>Java class for CompanyAddressDatumType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompanyAddressDatumType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}AddressDataType">
 *       &lt;sequence>
 *         &lt;element name="organName" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}String_1_255"/>
 *         &lt;element name="addressKindId" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}FnsIdType" minOccurs="0"/>
 *         &lt;element name="addressKindName" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}String_1_255" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompanyAddressDatumType", propOrder = {
    "organName",
    "addressKindId",
    "addressKindName"
})
public class CompanyAddressDatumType
    extends AddressDataType
{

    @XmlElement(required = true)
    protected String organName;
    protected BigInteger addressKindId;
    protected String addressKindName;

    /**
     * Gets the value of the organName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganName() {
        return organName;
    }

    /**
     * Sets the value of the organName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganName(String value) {
        this.organName = value;
    }

    /**
     * Gets the value of the addressKindId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAddressKindId() {
        return addressKindId;
    }

    /**
     * Sets the value of the addressKindId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAddressKindId(BigInteger value) {
        this.addressKindId = value;
    }

    /**
     * Gets the value of the addressKindName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressKindName() {
        return addressKindName;
    }

    /**
     * Sets the value of the addressKindName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressKindName(String value) {
        this.addressKindName = value;
    }

}
