//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 12:01:56 PM MSK 
//


package biz.red_soft.schemas.fssp.common._2011._0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Данный контейнер содержит один элемент сведений о должнике. Допустимые типы элементов
 *         перечислены в таблице (Удостоверение личности, Адрес и т. п.). При необходимости указать в документе несколько
 *         сведений следует завести в документе несколько объектов типа Data «Сведения».
 * 
 * <p>Java class for Data complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Data">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="IdentificationData" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}IdentificationDataType"/>
 *         &lt;element name="AddressData" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}AddressDataType"/>
 *         &lt;element name="TelephoneData" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}TelephoneDataType"/>
 *         &lt;element name="TransportData" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}TransportDataType"/>
 *         &lt;element name="SvedRabData" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}SvedRabDataType"/>
 *         &lt;element name="ManagementData" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}ManagementDataType"/>
 *         &lt;element name="SvedDoxodData" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}SvedDoxodDataType"/>
 *         &lt;element name="DebtorStateData" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}DebtorStateDataType"/>
 *         &lt;element name="AvailabilityAccData" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}AvailabilityAccDataType"/>
 *         &lt;element name="AvailabilityAccExtData" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}AvailabilityAccExtDataType"/>
 *         &lt;element name="ArrestRecoveryAmountData" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}ArrestRecoveryAmountDataType"/>
 *         &lt;element name="AvailabilityAccDepoData" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}AvailabilityAccDepoDataType"/>
 *         &lt;element name="RealtyRegistryExtractData" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}RealtyRegistryExtractType"/>
 *         &lt;element name="SvedNedvData" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}SvedNedvDataType"/>
 *         &lt;element name="SvedNedvObject" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}SvedNedvObjectType"/>
 *         &lt;element name="SvedNedvRightData" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}SvedNedvRightType"/>
 *         &lt;element name="SvedNedvEncumbranceData" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}SvedNedvEncumbranceType"/>
 *         &lt;element name="SvedNedvShareHoldingData" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}SvedNedvShareHoldingType"/>
 *         &lt;element name="ObjectData" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}ObjectDataType"/>
 *         &lt;element name="KKTData" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}KKTDataType"/>
 *         &lt;element name="AccountingData" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}AccountingDataType"/>
 *         &lt;element name="TicketDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}TicketDatumType"/>
 *         &lt;element name="personDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}PersonDatumType"/>
 *         &lt;element name="companyDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}CompanyDatumType"/>
 *         &lt;element name="paymentDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}PaymentDatumType"/>
 *         &lt;element name="countDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}CountDatumType"/>
 *         &lt;element name="companyAddressDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}CompanyAddressDatumType" minOccurs="0"/>
 *         &lt;element name="regOrganDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}RegOrganDatumType"/>
 *         &lt;element name="shipDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}ShipDatumType"/>
 *         &lt;element name="machineDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}MachineDatumType"/>
 *         &lt;element name="founderCompanyDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}FounderCompanyDatumType"/>
 *         &lt;element name="forgnFndrCompanyDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}ForgnFndrCompanyDatumType"/>
 *         &lt;element name="companyExtDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}CompanyExtDatumType"/>
 *         &lt;element name="founderPersonDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}FounderPersonDatumType"/>
 *         &lt;element name="companyManagementDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}CompanyManagementDatumType"/>
 *         &lt;element name="soleEntrepreneurDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}SoleEntrepreneurDatumType"/>
 *         &lt;element name="registrationDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}RegistrationDatumType"/>
 *         &lt;element name="licenseDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}LicenseDatumType"/>
 *         &lt;element name="subdivisionDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}SubdivisionDatumType"/>
 *         &lt;element name="egrulEgripDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}EgrulEgripDatumType"/>
 *         &lt;element name="accountDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}AccountDatumType"/>
 *         &lt;element name="accountExtDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}AccountExtDatumType"/>
 *         &lt;element name="soleEntrepreneurOldRegDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}SoleEntrepreneurOldRegDatumType"/>
 *         &lt;element name="documentDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}DocumentDatumType"/>
 *         &lt;element name="fishQuotaContractDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}FishQuotaContractDatumType"/>
 *         &lt;element name="fishQuotaYearDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}FishQuotaCurYearDatumType"/>
 *         &lt;element name="fishNonquotaContractDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}FishNonquotaContractDatumType"/>
 *         &lt;element name="transactionDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}TransactionDatumType"/>
 *         &lt;element name="deathDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}DeathDatumType"/>
 *         &lt;element name="unaccountedForDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}UnaccountedForDatumType"/>
 *         &lt;element name="DepositBoxDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}DepositBoxDatumType"/>
 *         &lt;element name="accountTransactionType" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}AccountTransactionDatumType"/>
 *         &lt;element name="AccountEncumbranceDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}AccountEncumbranceDatumType"/>
 *         &lt;element name="propertyObligationDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}PropertyObligationDatumType"/>
 *         &lt;element name="unstructuredDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}UnstructuredDatumType"/>
 *         &lt;element name="unemployedPersonCaseDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}UnemployedPersonCaseDatumType"/>
 *         &lt;element name="unemployedPersonRegistrationDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}UnemployedPersonRegistrationDatumType"/>
 *         &lt;element name="seniorityPeriodDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}SeniorityPeriodDatumType"/>
 *         &lt;element name="SalaryWithheldDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}SalaryWithheldDatumType"/>
 *         &lt;element name="CashLetterDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}CashLetterDatumType"/>
 *         &lt;element name="ValidationDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}ValidationDatumType"/>
 *         &lt;element name="GoodsDatum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}GoodsDatumType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Data", propOrder = {
    "identificationData",
    "addressData",
    "telephoneData",
    "transportData",
    "svedRabData",
    "managementData",
    "svedDoxodData",
    "debtorStateData",
    "availabilityAccData",
    "availabilityAccExtData",
    "arrestRecoveryAmountData",
    "availabilityAccDepoData",
    "realtyRegistryExtractData",
    "svedNedvData",
    "svedNedvObject",
    "svedNedvRightData",
    "svedNedvEncumbranceData",
    "svedNedvShareHoldingData",
    "objectData",
    "kktData",
    "accountingData",
    "ticketDatum",
    "personDatum",
    "companyDatum",
    "paymentDatum",
    "countDatum",
    "companyAddressDatum",
    "regOrganDatum",
    "shipDatum",
    "machineDatum",
    "founderCompanyDatum",
    "forgnFndrCompanyDatum",
    "companyExtDatum",
    "founderPersonDatum",
    "companyManagementDatum",
    "soleEntrepreneurDatum",
    "registrationDatum",
    "licenseDatum",
    "subdivisionDatum",
    "egrulEgripDatum",
    "accountDatum",
    "accountExtDatum",
    "soleEntrepreneurOldRegDatum",
    "documentDatum",
    "fishQuotaContractDatum",
    "fishQuotaYearDatum",
    "fishNonquotaContractDatum",
    "transactionDatum",
    "deathDatum",
    "unaccountedForDatum",
    "depositBoxDatum",
    "accountTransactionType",
    "accountEncumbranceDatum",
    "propertyObligationDatum",
    "unstructuredDatum",
    "unemployedPersonCaseDatum",
    "unemployedPersonRegistrationDatum",
    "seniorityPeriodDatum",
    "salaryWithheldDatum",
    "cashLetterDatum",
    "validationDatum",
    "goodsDatum"
})
public class Data {

    @XmlElement(name = "IdentificationData")
    protected IdentificationDataType identificationData;
    @XmlElement(name = "AddressData")
    protected AddressDataType addressData;
    @XmlElement(name = "TelephoneData")
    protected TelephoneDataType telephoneData;
    @XmlElement(name = "TransportData")
    protected TransportDataType transportData;
    @XmlElement(name = "SvedRabData")
    protected SvedRabDataType svedRabData;
    @XmlElement(name = "ManagementData")
    protected ManagementDataType managementData;
    @XmlElement(name = "SvedDoxodData")
    protected SvedDoxodDataType svedDoxodData;
    @XmlElement(name = "DebtorStateData")
    protected DebtorStateDataType debtorStateData;
    @XmlElement(name = "AvailabilityAccData")
    protected AvailabilityAccDataType availabilityAccData;
    @XmlElement(name = "AvailabilityAccExtData")
    protected AvailabilityAccExtDataType availabilityAccExtData;
    @XmlElement(name = "ArrestRecoveryAmountData")
    protected ArrestRecoveryAmountDataType arrestRecoveryAmountData;
    @XmlElement(name = "AvailabilityAccDepoData")
    protected AvailabilityAccDepoDataType availabilityAccDepoData;
    @XmlElement(name = "RealtyRegistryExtractData")
    protected RealtyRegistryExtractType realtyRegistryExtractData;
    @XmlElement(name = "SvedNedvData")
    protected SvedNedvDataType svedNedvData;
    @XmlElement(name = "SvedNedvObject")
    protected SvedNedvObjectType svedNedvObject;
    @XmlElement(name = "SvedNedvRightData")
    protected SvedNedvRightType svedNedvRightData;
    @XmlElement(name = "SvedNedvEncumbranceData")
    protected SvedNedvEncumbranceType svedNedvEncumbranceData;
    @XmlElement(name = "SvedNedvShareHoldingData")
    protected SvedNedvShareHoldingType svedNedvShareHoldingData;
    @XmlElement(name = "ObjectData")
    protected ObjectDataType objectData;
    @XmlElement(name = "KKTData")
    protected KKTDataType kktData;
    @XmlElement(name = "AccountingData")
    protected AccountingDataType accountingData;
    @XmlElement(name = "TicketDatum")
    protected TicketDatumType ticketDatum;
    protected PersonDatumType personDatum;
    protected CompanyDatumType companyDatum;
    protected PaymentDatumType paymentDatum;
    protected CountDatumType countDatum;
    protected CompanyAddressDatumType companyAddressDatum;
    protected RegOrganDatumType regOrganDatum;
    protected ShipDatumType shipDatum;
    protected MachineDatumType machineDatum;
    protected FounderCompanyDatumType founderCompanyDatum;
    protected ForgnFndrCompanyDatumType forgnFndrCompanyDatum;
    protected CompanyExtDatumType companyExtDatum;
    protected FounderPersonDatumType founderPersonDatum;
    protected CompanyManagementDatumType companyManagementDatum;
    protected SoleEntrepreneurDatumType soleEntrepreneurDatum;
    protected RegistrationDatumType registrationDatum;
    protected LicenseDatumType licenseDatum;
    protected SubdivisionDatumType subdivisionDatum;
    protected EgrulEgripDatumType egrulEgripDatum;
    protected AccountDatumType accountDatum;
    protected AccountExtDatumType accountExtDatum;
    protected SoleEntrepreneurOldRegDatumType soleEntrepreneurOldRegDatum;
    protected DocumentDatumType documentDatum;
    protected FishQuotaContractDatumType fishQuotaContractDatum;
    protected FishQuotaCurYearDatumType fishQuotaYearDatum;
    protected FishNonquotaContractDatumType fishNonquotaContractDatum;
    protected TransactionDatumType transactionDatum;
    protected DeathDatumType deathDatum;
    protected UnaccountedForDatumType unaccountedForDatum;
    @XmlElement(name = "DepositBoxDatum")
    protected DepositBoxDatumType depositBoxDatum;
    protected AccountTransactionDatumType accountTransactionType;
    @XmlElement(name = "AccountEncumbranceDatum")
    protected AccountEncumbranceDatumType accountEncumbranceDatum;
    protected PropertyObligationDatumType propertyObligationDatum;
    protected UnstructuredDatumType unstructuredDatum;
    protected UnemployedPersonCaseDatumType unemployedPersonCaseDatum;
    protected UnemployedPersonRegistrationDatumType unemployedPersonRegistrationDatum;
    protected SeniorityPeriodDatumType seniorityPeriodDatum;
    @XmlElement(name = "SalaryWithheldDatum")
    protected SalaryWithheldDatumType salaryWithheldDatum;
    @XmlElement(name = "CashLetterDatum")
    protected CashLetterDatumType cashLetterDatum;
    @XmlElement(name = "ValidationDatum")
    protected ValidationDatumType validationDatum;
    @XmlElement(name = "GoodsDatum")
    protected GoodsDatumType goodsDatum;

    /**
     * Gets the value of the identificationData property.
     * 
     * @return
     *     possible object is
     *     {@link IdentificationDataType }
     *     
     */
    public IdentificationDataType getIdentificationData() {
        return identificationData;
    }

    /**
     * Sets the value of the identificationData property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificationDataType }
     *     
     */
    public void setIdentificationData(IdentificationDataType value) {
        this.identificationData = value;
    }

    /**
     * Gets the value of the addressData property.
     * 
     * @return
     *     possible object is
     *     {@link AddressDataType }
     *     
     */
    public AddressDataType getAddressData() {
        return addressData;
    }

    /**
     * Sets the value of the addressData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressDataType }
     *     
     */
    public void setAddressData(AddressDataType value) {
        this.addressData = value;
    }

    /**
     * Gets the value of the telephoneData property.
     * 
     * @return
     *     possible object is
     *     {@link TelephoneDataType }
     *     
     */
    public TelephoneDataType getTelephoneData() {
        return telephoneData;
    }

    /**
     * Sets the value of the telephoneData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TelephoneDataType }
     *     
     */
    public void setTelephoneData(TelephoneDataType value) {
        this.telephoneData = value;
    }

    /**
     * Gets the value of the transportData property.
     * 
     * @return
     *     possible object is
     *     {@link TransportDataType }
     *     
     */
    public TransportDataType getTransportData() {
        return transportData;
    }

    /**
     * Sets the value of the transportData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportDataType }
     *     
     */
    public void setTransportData(TransportDataType value) {
        this.transportData = value;
    }

    /**
     * Gets the value of the svedRabData property.
     * 
     * @return
     *     possible object is
     *     {@link SvedRabDataType }
     *     
     */
    public SvedRabDataType getSvedRabData() {
        return svedRabData;
    }

    /**
     * Sets the value of the svedRabData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SvedRabDataType }
     *     
     */
    public void setSvedRabData(SvedRabDataType value) {
        this.svedRabData = value;
    }

    /**
     * Gets the value of the managementData property.
     * 
     * @return
     *     possible object is
     *     {@link ManagementDataType }
     *     
     */
    public ManagementDataType getManagementData() {
        return managementData;
    }

    /**
     * Sets the value of the managementData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManagementDataType }
     *     
     */
    public void setManagementData(ManagementDataType value) {
        this.managementData = value;
    }

    /**
     * Gets the value of the svedDoxodData property.
     * 
     * @return
     *     possible object is
     *     {@link SvedDoxodDataType }
     *     
     */
    public SvedDoxodDataType getSvedDoxodData() {
        return svedDoxodData;
    }

    /**
     * Sets the value of the svedDoxodData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SvedDoxodDataType }
     *     
     */
    public void setSvedDoxodData(SvedDoxodDataType value) {
        this.svedDoxodData = value;
    }

    /**
     * Gets the value of the debtorStateData property.
     * 
     * @return
     *     possible object is
     *     {@link DebtorStateDataType }
     *     
     */
    public DebtorStateDataType getDebtorStateData() {
        return debtorStateData;
    }

    /**
     * Sets the value of the debtorStateData property.
     * 
     * @param value
     *     allowed object is
     *     {@link DebtorStateDataType }
     *     
     */
    public void setDebtorStateData(DebtorStateDataType value) {
        this.debtorStateData = value;
    }

    /**
     * Gets the value of the availabilityAccData property.
     * 
     * @return
     *     possible object is
     *     {@link AvailabilityAccDataType }
     *     
     */
    public AvailabilityAccDataType getAvailabilityAccData() {
        return availabilityAccData;
    }

    /**
     * Sets the value of the availabilityAccData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvailabilityAccDataType }
     *     
     */
    public void setAvailabilityAccData(AvailabilityAccDataType value) {
        this.availabilityAccData = value;
    }

    /**
     * Gets the value of the availabilityAccExtData property.
     * 
     * @return
     *     possible object is
     *     {@link AvailabilityAccExtDataType }
     *     
     */
    public AvailabilityAccExtDataType getAvailabilityAccExtData() {
        return availabilityAccExtData;
    }

    /**
     * Sets the value of the availabilityAccExtData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvailabilityAccExtDataType }
     *     
     */
    public void setAvailabilityAccExtData(AvailabilityAccExtDataType value) {
        this.availabilityAccExtData = value;
    }

    /**
     * Gets the value of the arrestRecoveryAmountData property.
     * 
     * @return
     *     possible object is
     *     {@link ArrestRecoveryAmountDataType }
     *     
     */
    public ArrestRecoveryAmountDataType getArrestRecoveryAmountData() {
        return arrestRecoveryAmountData;
    }

    /**
     * Sets the value of the arrestRecoveryAmountData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrestRecoveryAmountDataType }
     *     
     */
    public void setArrestRecoveryAmountData(ArrestRecoveryAmountDataType value) {
        this.arrestRecoveryAmountData = value;
    }

    /**
     * Gets the value of the availabilityAccDepoData property.
     * 
     * @return
     *     possible object is
     *     {@link AvailabilityAccDepoDataType }
     *     
     */
    public AvailabilityAccDepoDataType getAvailabilityAccDepoData() {
        return availabilityAccDepoData;
    }

    /**
     * Sets the value of the availabilityAccDepoData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvailabilityAccDepoDataType }
     *     
     */
    public void setAvailabilityAccDepoData(AvailabilityAccDepoDataType value) {
        this.availabilityAccDepoData = value;
    }

    /**
     * Gets the value of the realtyRegistryExtractData property.
     * 
     * @return
     *     possible object is
     *     {@link RealtyRegistryExtractType }
     *     
     */
    public RealtyRegistryExtractType getRealtyRegistryExtractData() {
        return realtyRegistryExtractData;
    }

    /**
     * Sets the value of the realtyRegistryExtractData property.
     * 
     * @param value
     *     allowed object is
     *     {@link RealtyRegistryExtractType }
     *     
     */
    public void setRealtyRegistryExtractData(RealtyRegistryExtractType value) {
        this.realtyRegistryExtractData = value;
    }

    /**
     * Gets the value of the svedNedvData property.
     * 
     * @return
     *     possible object is
     *     {@link SvedNedvDataType }
     *     
     */
    public SvedNedvDataType getSvedNedvData() {
        return svedNedvData;
    }

    /**
     * Sets the value of the svedNedvData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SvedNedvDataType }
     *     
     */
    public void setSvedNedvData(SvedNedvDataType value) {
        this.svedNedvData = value;
    }

    /**
     * Gets the value of the svedNedvObject property.
     * 
     * @return
     *     possible object is
     *     {@link SvedNedvObjectType }
     *     
     */
    public SvedNedvObjectType getSvedNedvObject() {
        return svedNedvObject;
    }

    /**
     * Sets the value of the svedNedvObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link SvedNedvObjectType }
     *     
     */
    public void setSvedNedvObject(SvedNedvObjectType value) {
        this.svedNedvObject = value;
    }

    /**
     * Gets the value of the svedNedvRightData property.
     * 
     * @return
     *     possible object is
     *     {@link SvedNedvRightType }
     *     
     */
    public SvedNedvRightType getSvedNedvRightData() {
        return svedNedvRightData;
    }

    /**
     * Sets the value of the svedNedvRightData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SvedNedvRightType }
     *     
     */
    public void setSvedNedvRightData(SvedNedvRightType value) {
        this.svedNedvRightData = value;
    }

    /**
     * Gets the value of the svedNedvEncumbranceData property.
     * 
     * @return
     *     possible object is
     *     {@link SvedNedvEncumbranceType }
     *     
     */
    public SvedNedvEncumbranceType getSvedNedvEncumbranceData() {
        return svedNedvEncumbranceData;
    }

    /**
     * Sets the value of the svedNedvEncumbranceData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SvedNedvEncumbranceType }
     *     
     */
    public void setSvedNedvEncumbranceData(SvedNedvEncumbranceType value) {
        this.svedNedvEncumbranceData = value;
    }

    /**
     * Gets the value of the svedNedvShareHoldingData property.
     * 
     * @return
     *     possible object is
     *     {@link SvedNedvShareHoldingType }
     *     
     */
    public SvedNedvShareHoldingType getSvedNedvShareHoldingData() {
        return svedNedvShareHoldingData;
    }

    /**
     * Sets the value of the svedNedvShareHoldingData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SvedNedvShareHoldingType }
     *     
     */
    public void setSvedNedvShareHoldingData(SvedNedvShareHoldingType value) {
        this.svedNedvShareHoldingData = value;
    }

    /**
     * Gets the value of the objectData property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectDataType }
     *     
     */
    public ObjectDataType getObjectData() {
        return objectData;
    }

    /**
     * Sets the value of the objectData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectDataType }
     *     
     */
    public void setObjectData(ObjectDataType value) {
        this.objectData = value;
    }

    /**
     * Gets the value of the kktData property.
     * 
     * @return
     *     possible object is
     *     {@link KKTDataType }
     *     
     */
    public KKTDataType getKKTData() {
        return kktData;
    }

    /**
     * Sets the value of the kktData property.
     * 
     * @param value
     *     allowed object is
     *     {@link KKTDataType }
     *     
     */
    public void setKKTData(KKTDataType value) {
        this.kktData = value;
    }

    /**
     * Gets the value of the accountingData property.
     * 
     * @return
     *     possible object is
     *     {@link AccountingDataType }
     *     
     */
    public AccountingDataType getAccountingData() {
        return accountingData;
    }

    /**
     * Sets the value of the accountingData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountingDataType }
     *     
     */
    public void setAccountingData(AccountingDataType value) {
        this.accountingData = value;
    }

    /**
     * Gets the value of the ticketDatum property.
     * 
     * @return
     *     possible object is
     *     {@link TicketDatumType }
     *     
     */
    public TicketDatumType getTicketDatum() {
        return ticketDatum;
    }

    /**
     * Sets the value of the ticketDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link TicketDatumType }
     *     
     */
    public void setTicketDatum(TicketDatumType value) {
        this.ticketDatum = value;
    }

    /**
     * Gets the value of the personDatum property.
     * 
     * @return
     *     possible object is
     *     {@link PersonDatumType }
     *     
     */
    public PersonDatumType getPersonDatum() {
        return personDatum;
    }

    /**
     * Sets the value of the personDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonDatumType }
     *     
     */
    public void setPersonDatum(PersonDatumType value) {
        this.personDatum = value;
    }

    /**
     * Gets the value of the companyDatum property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyDatumType }
     *     
     */
    public CompanyDatumType getCompanyDatum() {
        return companyDatum;
    }

    /**
     * Sets the value of the companyDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyDatumType }
     *     
     */
    public void setCompanyDatum(CompanyDatumType value) {
        this.companyDatum = value;
    }

    /**
     * Gets the value of the paymentDatum property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDatumType }
     *     
     */
    public PaymentDatumType getPaymentDatum() {
        return paymentDatum;
    }

    /**
     * Sets the value of the paymentDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDatumType }
     *     
     */
    public void setPaymentDatum(PaymentDatumType value) {
        this.paymentDatum = value;
    }

    /**
     * Gets the value of the countDatum property.
     * 
     * @return
     *     possible object is
     *     {@link CountDatumType }
     *     
     */
    public CountDatumType getCountDatum() {
        return countDatum;
    }

    /**
     * Sets the value of the countDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountDatumType }
     *     
     */
    public void setCountDatum(CountDatumType value) {
        this.countDatum = value;
    }

    /**
     * Gets the value of the companyAddressDatum property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyAddressDatumType }
     *     
     */
    public CompanyAddressDatumType getCompanyAddressDatum() {
        return companyAddressDatum;
    }

    /**
     * Sets the value of the companyAddressDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyAddressDatumType }
     *     
     */
    public void setCompanyAddressDatum(CompanyAddressDatumType value) {
        this.companyAddressDatum = value;
    }

    /**
     * Gets the value of the regOrganDatum property.
     * 
     * @return
     *     possible object is
     *     {@link RegOrganDatumType }
     *     
     */
    public RegOrganDatumType getRegOrganDatum() {
        return regOrganDatum;
    }

    /**
     * Sets the value of the regOrganDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegOrganDatumType }
     *     
     */
    public void setRegOrganDatum(RegOrganDatumType value) {
        this.regOrganDatum = value;
    }

    /**
     * Gets the value of the shipDatum property.
     * 
     * @return
     *     possible object is
     *     {@link ShipDatumType }
     *     
     */
    public ShipDatumType getShipDatum() {
        return shipDatum;
    }

    /**
     * Sets the value of the shipDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipDatumType }
     *     
     */
    public void setShipDatum(ShipDatumType value) {
        this.shipDatum = value;
    }

    /**
     * Gets the value of the machineDatum property.
     * 
     * @return
     *     possible object is
     *     {@link MachineDatumType }
     *     
     */
    public MachineDatumType getMachineDatum() {
        return machineDatum;
    }

    /**
     * Sets the value of the machineDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link MachineDatumType }
     *     
     */
    public void setMachineDatum(MachineDatumType value) {
        this.machineDatum = value;
    }

    /**
     * Gets the value of the founderCompanyDatum property.
     * 
     * @return
     *     possible object is
     *     {@link FounderCompanyDatumType }
     *     
     */
    public FounderCompanyDatumType getFounderCompanyDatum() {
        return founderCompanyDatum;
    }

    /**
     * Sets the value of the founderCompanyDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link FounderCompanyDatumType }
     *     
     */
    public void setFounderCompanyDatum(FounderCompanyDatumType value) {
        this.founderCompanyDatum = value;
    }

    /**
     * Gets the value of the forgnFndrCompanyDatum property.
     * 
     * @return
     *     possible object is
     *     {@link ForgnFndrCompanyDatumType }
     *     
     */
    public ForgnFndrCompanyDatumType getForgnFndrCompanyDatum() {
        return forgnFndrCompanyDatum;
    }

    /**
     * Sets the value of the forgnFndrCompanyDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForgnFndrCompanyDatumType }
     *     
     */
    public void setForgnFndrCompanyDatum(ForgnFndrCompanyDatumType value) {
        this.forgnFndrCompanyDatum = value;
    }

    /**
     * Gets the value of the companyExtDatum property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyExtDatumType }
     *     
     */
    public CompanyExtDatumType getCompanyExtDatum() {
        return companyExtDatum;
    }

    /**
     * Sets the value of the companyExtDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyExtDatumType }
     *     
     */
    public void setCompanyExtDatum(CompanyExtDatumType value) {
        this.companyExtDatum = value;
    }

    /**
     * Gets the value of the founderPersonDatum property.
     * 
     * @return
     *     possible object is
     *     {@link FounderPersonDatumType }
     *     
     */
    public FounderPersonDatumType getFounderPersonDatum() {
        return founderPersonDatum;
    }

    /**
     * Sets the value of the founderPersonDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link FounderPersonDatumType }
     *     
     */
    public void setFounderPersonDatum(FounderPersonDatumType value) {
        this.founderPersonDatum = value;
    }

    /**
     * Gets the value of the companyManagementDatum property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyManagementDatumType }
     *     
     */
    public CompanyManagementDatumType getCompanyManagementDatum() {
        return companyManagementDatum;
    }

    /**
     * Sets the value of the companyManagementDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyManagementDatumType }
     *     
     */
    public void setCompanyManagementDatum(CompanyManagementDatumType value) {
        this.companyManagementDatum = value;
    }

    /**
     * Gets the value of the soleEntrepreneurDatum property.
     * 
     * @return
     *     possible object is
     *     {@link SoleEntrepreneurDatumType }
     *     
     */
    public SoleEntrepreneurDatumType getSoleEntrepreneurDatum() {
        return soleEntrepreneurDatum;
    }

    /**
     * Sets the value of the soleEntrepreneurDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoleEntrepreneurDatumType }
     *     
     */
    public void setSoleEntrepreneurDatum(SoleEntrepreneurDatumType value) {
        this.soleEntrepreneurDatum = value;
    }

    /**
     * Gets the value of the registrationDatum property.
     * 
     * @return
     *     possible object is
     *     {@link RegistrationDatumType }
     *     
     */
    public RegistrationDatumType getRegistrationDatum() {
        return registrationDatum;
    }

    /**
     * Sets the value of the registrationDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistrationDatumType }
     *     
     */
    public void setRegistrationDatum(RegistrationDatumType value) {
        this.registrationDatum = value;
    }

    /**
     * Gets the value of the licenseDatum property.
     * 
     * @return
     *     possible object is
     *     {@link LicenseDatumType }
     *     
     */
    public LicenseDatumType getLicenseDatum() {
        return licenseDatum;
    }

    /**
     * Sets the value of the licenseDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link LicenseDatumType }
     *     
     */
    public void setLicenseDatum(LicenseDatumType value) {
        this.licenseDatum = value;
    }

    /**
     * Gets the value of the subdivisionDatum property.
     * 
     * @return
     *     possible object is
     *     {@link SubdivisionDatumType }
     *     
     */
    public SubdivisionDatumType getSubdivisionDatum() {
        return subdivisionDatum;
    }

    /**
     * Sets the value of the subdivisionDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubdivisionDatumType }
     *     
     */
    public void setSubdivisionDatum(SubdivisionDatumType value) {
        this.subdivisionDatum = value;
    }

    /**
     * Gets the value of the egrulEgripDatum property.
     * 
     * @return
     *     possible object is
     *     {@link EgrulEgripDatumType }
     *     
     */
    public EgrulEgripDatumType getEgrulEgripDatum() {
        return egrulEgripDatum;
    }

    /**
     * Sets the value of the egrulEgripDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link EgrulEgripDatumType }
     *     
     */
    public void setEgrulEgripDatum(EgrulEgripDatumType value) {
        this.egrulEgripDatum = value;
    }

    /**
     * Gets the value of the accountDatum property.
     * 
     * @return
     *     possible object is
     *     {@link AccountDatumType }
     *     
     */
    public AccountDatumType getAccountDatum() {
        return accountDatum;
    }

    /**
     * Sets the value of the accountDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountDatumType }
     *     
     */
    public void setAccountDatum(AccountDatumType value) {
        this.accountDatum = value;
    }

    /**
     * Gets the value of the accountExtDatum property.
     * 
     * @return
     *     possible object is
     *     {@link AccountExtDatumType }
     *     
     */
    public AccountExtDatumType getAccountExtDatum() {
        return accountExtDatum;
    }

    /**
     * Sets the value of the accountExtDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountExtDatumType }
     *     
     */
    public void setAccountExtDatum(AccountExtDatumType value) {
        this.accountExtDatum = value;
    }

    /**
     * Gets the value of the soleEntrepreneurOldRegDatum property.
     * 
     * @return
     *     possible object is
     *     {@link SoleEntrepreneurOldRegDatumType }
     *     
     */
    public SoleEntrepreneurOldRegDatumType getSoleEntrepreneurOldRegDatum() {
        return soleEntrepreneurOldRegDatum;
    }

    /**
     * Sets the value of the soleEntrepreneurOldRegDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoleEntrepreneurOldRegDatumType }
     *     
     */
    public void setSoleEntrepreneurOldRegDatum(SoleEntrepreneurOldRegDatumType value) {
        this.soleEntrepreneurOldRegDatum = value;
    }

    /**
     * Gets the value of the documentDatum property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentDatumType }
     *     
     */
    public DocumentDatumType getDocumentDatum() {
        return documentDatum;
    }

    /**
     * Sets the value of the documentDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentDatumType }
     *     
     */
    public void setDocumentDatum(DocumentDatumType value) {
        this.documentDatum = value;
    }

    /**
     * Gets the value of the fishQuotaContractDatum property.
     * 
     * @return
     *     possible object is
     *     {@link FishQuotaContractDatumType }
     *     
     */
    public FishQuotaContractDatumType getFishQuotaContractDatum() {
        return fishQuotaContractDatum;
    }

    /**
     * Sets the value of the fishQuotaContractDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link FishQuotaContractDatumType }
     *     
     */
    public void setFishQuotaContractDatum(FishQuotaContractDatumType value) {
        this.fishQuotaContractDatum = value;
    }

    /**
     * Gets the value of the fishQuotaYearDatum property.
     * 
     * @return
     *     possible object is
     *     {@link FishQuotaCurYearDatumType }
     *     
     */
    public FishQuotaCurYearDatumType getFishQuotaYearDatum() {
        return fishQuotaYearDatum;
    }

    /**
     * Sets the value of the fishQuotaYearDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link FishQuotaCurYearDatumType }
     *     
     */
    public void setFishQuotaYearDatum(FishQuotaCurYearDatumType value) {
        this.fishQuotaYearDatum = value;
    }

    /**
     * Gets the value of the fishNonquotaContractDatum property.
     * 
     * @return
     *     possible object is
     *     {@link FishNonquotaContractDatumType }
     *     
     */
    public FishNonquotaContractDatumType getFishNonquotaContractDatum() {
        return fishNonquotaContractDatum;
    }

    /**
     * Sets the value of the fishNonquotaContractDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link FishNonquotaContractDatumType }
     *     
     */
    public void setFishNonquotaContractDatum(FishNonquotaContractDatumType value) {
        this.fishNonquotaContractDatum = value;
    }

    /**
     * Gets the value of the transactionDatum property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionDatumType }
     *     
     */
    public TransactionDatumType getTransactionDatum() {
        return transactionDatum;
    }

    /**
     * Sets the value of the transactionDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionDatumType }
     *     
     */
    public void setTransactionDatum(TransactionDatumType value) {
        this.transactionDatum = value;
    }

    /**
     * Gets the value of the deathDatum property.
     * 
     * @return
     *     possible object is
     *     {@link DeathDatumType }
     *     
     */
    public DeathDatumType getDeathDatum() {
        return deathDatum;
    }

    /**
     * Sets the value of the deathDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeathDatumType }
     *     
     */
    public void setDeathDatum(DeathDatumType value) {
        this.deathDatum = value;
    }

    /**
     * Gets the value of the unaccountedForDatum property.
     * 
     * @return
     *     possible object is
     *     {@link UnaccountedForDatumType }
     *     
     */
    public UnaccountedForDatumType getUnaccountedForDatum() {
        return unaccountedForDatum;
    }

    /**
     * Sets the value of the unaccountedForDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnaccountedForDatumType }
     *     
     */
    public void setUnaccountedForDatum(UnaccountedForDatumType value) {
        this.unaccountedForDatum = value;
    }

    /**
     * Gets the value of the depositBoxDatum property.
     * 
     * @return
     *     possible object is
     *     {@link DepositBoxDatumType }
     *     
     */
    public DepositBoxDatumType getDepositBoxDatum() {
        return depositBoxDatum;
    }

    /**
     * Sets the value of the depositBoxDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link DepositBoxDatumType }
     *     
     */
    public void setDepositBoxDatum(DepositBoxDatumType value) {
        this.depositBoxDatum = value;
    }

    /**
     * Gets the value of the accountTransactionType property.
     * 
     * @return
     *     possible object is
     *     {@link AccountTransactionDatumType }
     *     
     */
    public AccountTransactionDatumType getAccountTransactionType() {
        return accountTransactionType;
    }

    /**
     * Sets the value of the accountTransactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountTransactionDatumType }
     *     
     */
    public void setAccountTransactionType(AccountTransactionDatumType value) {
        this.accountTransactionType = value;
    }

    /**
     * Gets the value of the accountEncumbranceDatum property.
     * 
     * @return
     *     possible object is
     *     {@link AccountEncumbranceDatumType }
     *     
     */
    public AccountEncumbranceDatumType getAccountEncumbranceDatum() {
        return accountEncumbranceDatum;
    }

    /**
     * Sets the value of the accountEncumbranceDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountEncumbranceDatumType }
     *     
     */
    public void setAccountEncumbranceDatum(AccountEncumbranceDatumType value) {
        this.accountEncumbranceDatum = value;
    }

    /**
     * Gets the value of the propertyObligationDatum property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyObligationDatumType }
     *     
     */
    public PropertyObligationDatumType getPropertyObligationDatum() {
        return propertyObligationDatum;
    }

    /**
     * Sets the value of the propertyObligationDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyObligationDatumType }
     *     
     */
    public void setPropertyObligationDatum(PropertyObligationDatumType value) {
        this.propertyObligationDatum = value;
    }

    /**
     * Gets the value of the unstructuredDatum property.
     * 
     * @return
     *     possible object is
     *     {@link UnstructuredDatumType }
     *     
     */
    public UnstructuredDatumType getUnstructuredDatum() {
        return unstructuredDatum;
    }

    /**
     * Sets the value of the unstructuredDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnstructuredDatumType }
     *     
     */
    public void setUnstructuredDatum(UnstructuredDatumType value) {
        this.unstructuredDatum = value;
    }

    /**
     * Gets the value of the unemployedPersonCaseDatum property.
     * 
     * @return
     *     possible object is
     *     {@link UnemployedPersonCaseDatumType }
     *     
     */
    public UnemployedPersonCaseDatumType getUnemployedPersonCaseDatum() {
        return unemployedPersonCaseDatum;
    }

    /**
     * Sets the value of the unemployedPersonCaseDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnemployedPersonCaseDatumType }
     *     
     */
    public void setUnemployedPersonCaseDatum(UnemployedPersonCaseDatumType value) {
        this.unemployedPersonCaseDatum = value;
    }

    /**
     * Gets the value of the unemployedPersonRegistrationDatum property.
     * 
     * @return
     *     possible object is
     *     {@link UnemployedPersonRegistrationDatumType }
     *     
     */
    public UnemployedPersonRegistrationDatumType getUnemployedPersonRegistrationDatum() {
        return unemployedPersonRegistrationDatum;
    }

    /**
     * Sets the value of the unemployedPersonRegistrationDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnemployedPersonRegistrationDatumType }
     *     
     */
    public void setUnemployedPersonRegistrationDatum(UnemployedPersonRegistrationDatumType value) {
        this.unemployedPersonRegistrationDatum = value;
    }

    /**
     * Gets the value of the seniorityPeriodDatum property.
     * 
     * @return
     *     possible object is
     *     {@link SeniorityPeriodDatumType }
     *     
     */
    public SeniorityPeriodDatumType getSeniorityPeriodDatum() {
        return seniorityPeriodDatum;
    }

    /**
     * Sets the value of the seniorityPeriodDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeniorityPeriodDatumType }
     *     
     */
    public void setSeniorityPeriodDatum(SeniorityPeriodDatumType value) {
        this.seniorityPeriodDatum = value;
    }

    /**
     * Gets the value of the salaryWithheldDatum property.
     * 
     * @return
     *     possible object is
     *     {@link SalaryWithheldDatumType }
     *     
     */
    public SalaryWithheldDatumType getSalaryWithheldDatum() {
        return salaryWithheldDatum;
    }

    /**
     * Sets the value of the salaryWithheldDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalaryWithheldDatumType }
     *     
     */
    public void setSalaryWithheldDatum(SalaryWithheldDatumType value) {
        this.salaryWithheldDatum = value;
    }

    /**
     * Gets the value of the cashLetterDatum property.
     * 
     * @return
     *     possible object is
     *     {@link CashLetterDatumType }
     *     
     */
    public CashLetterDatumType getCashLetterDatum() {
        return cashLetterDatum;
    }

    /**
     * Sets the value of the cashLetterDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link CashLetterDatumType }
     *     
     */
    public void setCashLetterDatum(CashLetterDatumType value) {
        this.cashLetterDatum = value;
    }

    /**
     * Gets the value of the validationDatum property.
     * 
     * @return
     *     possible object is
     *     {@link ValidationDatumType }
     *     
     */
    public ValidationDatumType getValidationDatum() {
        return validationDatum;
    }

    /**
     * Sets the value of the validationDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidationDatumType }
     *     
     */
    public void setValidationDatum(ValidationDatumType value) {
        this.validationDatum = value;
    }

    /**
     * Gets the value of the goodsDatum property.
     * 
     * @return
     *     possible object is
     *     {@link GoodsDatumType }
     *     
     */
    public GoodsDatumType getGoodsDatum() {
        return goodsDatum;
    }

    /**
     * Sets the value of the goodsDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link GoodsDatumType }
     *     
     */
    public void setGoodsDatum(GoodsDatumType value) {
        this.goodsDatum = value;
    }

}
