//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 12:01:56 PM MSK 
//


package biz.red_soft.schemas.fssp.common._2011._0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.w3._2000._09.xmldsig.SignatureType;


/**
 * Документ IPSideRequestCourseIDType «Регистрация запроса о ходе ИП по исполнительному
 *         документу»
 * 
 * <p>Java class for IPSideRequestCourseIDType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IPSideRequestCourseIDType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}IPSideRequestType">
 *       &lt;sequence>
 *         &lt;element name="IDTypeCode" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}IdType"/>
 *         &lt;element name="IDNumber" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}String_1_25"/>
 *         &lt;element name="IDDate" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}Date"/>
 *         &lt;element name="IDSubjectText" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}String_1_500"/>
 *         &lt;element name="IDCourtName" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}String_1_250"/>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IPSideRequestCourseIDType", propOrder = {
    "idTypeCode",
    "idNumber",
    "idDate",
    "idSubjectText",
    "idCourtName",
    "signature"
})
public class IPSideRequestCourseIDType
    extends IPSideRequestType
{

    @XmlElement(name = "IDTypeCode", required = true)
    protected String idTypeCode;
    @XmlElement(name = "IDNumber", required = true)
    protected String idNumber;
    @XmlElement(name = "IDDate", required = true)
    protected XMLGregorianCalendar idDate;
    @XmlElement(name = "IDSubjectText", required = true)
    protected String idSubjectText;
    @XmlElement(name = "IDCourtName", required = true)
    protected String idCourtName;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#")
    protected List<SignatureType> signature;

    /**
     * Gets the value of the idTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDTypeCode() {
        return idTypeCode;
    }

    /**
     * Sets the value of the idTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDTypeCode(String value) {
        this.idTypeCode = value;
    }

    /**
     * Gets the value of the idNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDNumber() {
        return idNumber;
    }

    /**
     * Sets the value of the idNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDNumber(String value) {
        this.idNumber = value;
    }

    /**
     * Gets the value of the idDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIDDate() {
        return idDate;
    }

    /**
     * Sets the value of the idDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIDDate(XMLGregorianCalendar value) {
        this.idDate = value;
    }

    /**
     * Gets the value of the idSubjectText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDSubjectText() {
        return idSubjectText;
    }

    /**
     * Sets the value of the idSubjectText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDSubjectText(String value) {
        this.idSubjectText = value;
    }

    /**
     * Gets the value of the idCourtName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDCourtName() {
        return idCourtName;
    }

    /**
     * Sets the value of the idCourtName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDCourtName(String value) {
        this.idCourtName = value;
    }

    /**
     * ЭП Gets the value of the signature property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the signature property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSignature().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SignatureType }
     * 
     * 
     */
    public List<SignatureType> getSignature() {
        if (signature == null) {
            signature = new ArrayList<SignatureType>();
        }
        return this.signature;
    }

}
