//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 12:01:56 PM MSK 
//


package biz.red_soft.schemas.fssp.common._2011._0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Документ IPSideAppProlongType «Регистрация заявления на продление сроков ИП» (Z_002)
 * 
 * <p>Java class for IPSideAppProlongType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IPSideAppProlongType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}IPSideAppSPIActType">
 *       &lt;sequence>
 *         &lt;element name="prolongKind" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}ProlongKindType"/>
 *         &lt;element name="extension" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}Date"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IPSideAppProlongType", propOrder = {
    "prolongKind",
    "extension"
})
public class IPSideAppProlongType
    extends IPSideAppSPIActType
{

    @XmlElement(required = true)
    protected String prolongKind;
    @XmlElement(required = true)
    protected XMLGregorianCalendar extension;

    /**
     * Gets the value of the prolongKind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProlongKind() {
        return prolongKind;
    }

    /**
     * Sets the value of the prolongKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProlongKind(String value) {
        this.prolongKind = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExtension(XMLGregorianCalendar value) {
        this.extension = value;
    }

}
