//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 12:01:56 PM MSK 
//


package biz.red_soft.schemas.fssp.common._2011._0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Запрос данных справочника
 * 
 * <p>Java class for LookupTableQuery complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LookupTableQuery">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lookupTable" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}LookupTableType"/>
 *         &lt;element name="filter" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}String_1_1000" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LookupTableQuery", propOrder = {
    "lookupTable",
    "filter"
})
public class LookupTableQuery {

    @XmlElement(required = true)
    protected LookupTableType lookupTable;
    protected String filter;

    /**
     * Gets the value of the lookupTable property.
     * 
     * @return
     *     possible object is
     *     {@link LookupTableType }
     *     
     */
    public LookupTableType getLookupTable() {
        return lookupTable;
    }

    /**
     * Sets the value of the lookupTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link LookupTableType }
     *     
     */
    public void setLookupTable(LookupTableType value) {
        this.lookupTable = value;
    }

    /**
     * Gets the value of the filter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilter() {
        return filter;
    }

    /**
     * Sets the value of the filter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilter(String value) {
        this.filter = value;
    }

}
