//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 12:01:56 PM MSK 
//


package biz.red_soft.schemas.fssp.common._2011._0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Уведомление о результатах обработки уведомления о результате приема
 *             пакетов документов (не требует обработки)
 * 
 * <p>Java class for NotifyMessagesRs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NotifyMessagesRs">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}Response">
 *       &lt;sequence>
 *         &lt;element name="notifyResults" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}MessageResultCollection" minOccurs="0"/>
 *         &lt;element name="messageResults" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}MessageResultCollection" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NotifyMessagesRs", propOrder = {
    "notifyResults",
    "messageResults"
})
public class NotifyMessagesRs
    extends Response
{

    protected MessageResultCollection notifyResults;
    protected MessageResultCollection messageResults;

    /**
     * Gets the value of the notifyResults property.
     * 
     * @return
     *     possible object is
     *     {@link MessageResultCollection }
     *     
     */
    public MessageResultCollection getNotifyResults() {
        return notifyResults;
    }

    /**
     * Sets the value of the notifyResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageResultCollection }
     *     
     */
    public void setNotifyResults(MessageResultCollection value) {
        this.notifyResults = value;
    }

    /**
     * Gets the value of the messageResults property.
     * 
     * @return
     *     possible object is
     *     {@link MessageResultCollection }
     *     
     */
    public MessageResultCollection getMessageResults() {
        return messageResults;
    }

    /**
     * Sets the value of the messageResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageResultCollection }
     *     
     */
    public void setMessageResults(MessageResultCollection value) {
        this.messageResults = value;
    }

}
