//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 12:01:56 PM MSK 
//


package biz.red_soft.schemas.fssp.common._2011._0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * используется для передачи документов внешним контрагентам
 * 
 * <p>Java class for OutgoingForcedExecDocument complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OutgoingForcedExecDocument">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InternalKey" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}InternalKeyType"/>
 *         &lt;element name="IncomingDocKey" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}ExternalKeyType"/>
 *         &lt;element name="ProcDocRef" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}DocRefType"/>
 *         &lt;element name="SenderProperties" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}SenderSPIType"/>
 *         &lt;element name="IP" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}IP"/>
 *         &lt;element name="DocumentData" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}EmbeddedDocumentType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OutgoingForcedExecDocument", propOrder = {
    "internalKey",
    "incomingDocKey",
    "procDocRef",
    "senderProperties",
    "ip",
    "documentData"
})
public class OutgoingForcedExecDocument {

    @XmlElement(name = "InternalKey")
    protected long internalKey;
    @XmlElement(name = "IncomingDocKey", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String incomingDocKey;
    @XmlElement(name = "ProcDocRef", required = true)
    protected DocRefType procDocRef;
    @XmlElement(name = "SenderProperties", required = true)
    protected SenderSPIType senderProperties;
    @XmlElement(name = "IP", required = true)
    protected IP ip;
    @XmlElement(name = "DocumentData", required = true)
    protected EmbeddedDocumentType documentData;

    /**
     * Gets the value of the internalKey property.
     * 
     */
    public long getInternalKey() {
        return internalKey;
    }

    /**
     * Sets the value of the internalKey property.
     * 
     */
    public void setInternalKey(long value) {
        this.internalKey = value;
    }

    /**
     * Gets the value of the incomingDocKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncomingDocKey() {
        return incomingDocKey;
    }

    /**
     * Sets the value of the incomingDocKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncomingDocKey(String value) {
        this.incomingDocKey = value;
    }

    /**
     * Gets the value of the procDocRef property.
     * 
     * @return
     *     possible object is
     *     {@link DocRefType }
     *     
     */
    public DocRefType getProcDocRef() {
        return procDocRef;
    }

    /**
     * Sets the value of the procDocRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocRefType }
     *     
     */
    public void setProcDocRef(DocRefType value) {
        this.procDocRef = value;
    }

    /**
     * Gets the value of the senderProperties property.
     * 
     * @return
     *     possible object is
     *     {@link SenderSPIType }
     *     
     */
    public SenderSPIType getSenderProperties() {
        return senderProperties;
    }

    /**
     * Sets the value of the senderProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link SenderSPIType }
     *     
     */
    public void setSenderProperties(SenderSPIType value) {
        this.senderProperties = value;
    }

    /**
     * Gets the value of the ip property.
     * 
     * @return
     *     possible object is
     *     {@link IP }
     *     
     */
    public IP getIP() {
        return ip;
    }

    /**
     * Sets the value of the ip property.
     * 
     * @param value
     *     allowed object is
     *     {@link IP }
     *     
     */
    public void setIP(IP value) {
        this.ip = value;
    }

    /**
     * Gets the value of the documentData property.
     * 
     * @return
     *     possible object is
     *     {@link EmbeddedDocumentType }
     *     
     */
    public EmbeddedDocumentType getDocumentData() {
        return documentData;
    }

    /**
     * Sets the value of the documentData property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmbeddedDocumentType }
     *     
     */
    public void setDocumentData(EmbeddedDocumentType value) {
        this.documentData = value;
    }

}
