//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 12:01:56 PM MSK 
//


package biz.red_soft.schemas.fssp.common._2011._0;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Данные по штрафам
 * 
 * <p>Java class for PenaltyChargesData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PenaltyChargesData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PenaltyKey" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}InternalKeyType"/>
 *         &lt;element name="OspCode" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}VkspType"/>
 *         &lt;element name="UnloadDate" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}DateTime"/>
 *         &lt;element name="PerpetratorType" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}ContragentType"/>
 *         &lt;element name="PerpetratorName" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}String_1_1000"/>
 *         &lt;element name="PerpetratorBirthDate" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}Date" minOccurs="0"/>
 *         &lt;element name="PerpetratorBirthplace" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}String_1_300" minOccurs="0"/>
 *         &lt;element name="PerpetratorSerDoc" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}String_1_25" minOccurs="0"/>
 *         &lt;element name="PerpetratorNumDoc" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}String_1_25" minOccurs="0"/>
 *         &lt;element name="PerpetratorSNILS" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}SnilsType" minOccurs="0"/>
 *         &lt;element name="PerpetratorINN" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}InnType" minOccurs="0"/>
 *         &lt;element name="PerpetratorKPP" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}KppType" minOccurs="0"/>
 *         &lt;element name="PerpetratorOGRN" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}OgrnType" minOccurs="0"/>
 *         &lt;element name="PerpetratorAdr" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}String_1_300"/>
 *         &lt;element name="PerpetratorWorkplace" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}String_1_1000" minOccurs="0"/>
 *         &lt;element name="PerpetratorWorkplaceINN" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}InnType" minOccurs="0"/>
 *         &lt;element name="PerpetratorWorkplaceTelephone" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}TelephoneNumberType" minOccurs="0"/>
 *         &lt;element name="PerpetratorWorkplaceAddress" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}String_1_300" minOccurs="0"/>
 *         &lt;element name="PenaltyNumber" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}DocNumberType"/>
 *         &lt;element name="PenaltyDate" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}Date"/>
 *         &lt;element name="PenaltyRiseDate" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}Date"/>
 *         &lt;element name="IPBasic" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}DocNumberType" minOccurs="0"/>
 *         &lt;element name="PenaltyBasic" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}DocNumberType" minOccurs="0"/>
 *         &lt;element name="PenaltyIP" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}DocNumberType" minOccurs="0"/>
 *         &lt;element name="PenaltySum" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}Money"/>
 *         &lt;element name="PenaltyRestTotal" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}Money"/>
 *         &lt;element name="PenaltyKbk" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}KbkType"/>
 *         &lt;element name="PenaltyAuthorName" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}FullFioType"/>
 *         &lt;element name="PenaltyAuthorTel" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}TelephoneNumberType" minOccurs="0"/>
 *         &lt;element name="IsConfidential" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}Boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PenaltyChargesData", propOrder = {
    "penaltyKey",
    "ospCode",
    "unloadDate",
    "perpetratorType",
    "perpetratorName",
    "perpetratorBirthDate",
    "perpetratorBirthplace",
    "perpetratorSerDoc",
    "perpetratorNumDoc",
    "perpetratorSNILS",
    "perpetratorINN",
    "perpetratorKPP",
    "perpetratorOGRN",
    "perpetratorAdr",
    "perpetratorWorkplace",
    "perpetratorWorkplaceINN",
    "perpetratorWorkplaceTelephone",
    "perpetratorWorkplaceAddress",
    "penaltyNumber",
    "penaltyDate",
    "penaltyRiseDate",
    "ipBasic",
    "penaltyBasic",
    "penaltyIP",
    "penaltySum",
    "penaltyRestTotal",
    "penaltyKbk",
    "penaltyAuthorName",
    "penaltyAuthorTel",
    "isConfidential"
})
public class PenaltyChargesData {

    @XmlElement(name = "PenaltyKey")
    protected long penaltyKey;
    @XmlElement(name = "OspCode", required = true)
    protected String ospCode;
    @XmlElement(name = "UnloadDate", required = true)
    protected XMLGregorianCalendar unloadDate;
    @XmlElement(name = "PerpetratorType", required = true)
    protected String perpetratorType;
    @XmlElement(name = "PerpetratorName", required = true)
    protected String perpetratorName;
    @XmlElement(name = "PerpetratorBirthDate")
    protected XMLGregorianCalendar perpetratorBirthDate;
    @XmlElement(name = "PerpetratorBirthplace")
    protected String perpetratorBirthplace;
    @XmlElement(name = "PerpetratorSerDoc")
    protected String perpetratorSerDoc;
    @XmlElement(name = "PerpetratorNumDoc")
    protected String perpetratorNumDoc;
    @XmlElement(name = "PerpetratorSNILS")
    protected String perpetratorSNILS;
    @XmlElement(name = "PerpetratorINN")
    protected String perpetratorINN;
    @XmlElement(name = "PerpetratorKPP")
    protected String perpetratorKPP;
    @XmlElement(name = "PerpetratorOGRN")
    protected String perpetratorOGRN;
    @XmlElement(name = "PerpetratorAdr", required = true)
    protected String perpetratorAdr;
    @XmlElement(name = "PerpetratorWorkplace")
    protected String perpetratorWorkplace;
    @XmlElement(name = "PerpetratorWorkplaceINN")
    protected String perpetratorWorkplaceINN;
    @XmlElement(name = "PerpetratorWorkplaceTelephone")
    protected String perpetratorWorkplaceTelephone;
    @XmlElement(name = "PerpetratorWorkplaceAddress")
    protected String perpetratorWorkplaceAddress;
    @XmlElement(name = "PenaltyNumber", required = true)
    protected String penaltyNumber;
    @XmlElement(name = "PenaltyDate", required = true)
    protected XMLGregorianCalendar penaltyDate;
    @XmlElement(name = "PenaltyRiseDate", required = true)
    protected XMLGregorianCalendar penaltyRiseDate;
    @XmlElement(name = "IPBasic")
    protected String ipBasic;
    @XmlElement(name = "PenaltyBasic")
    protected String penaltyBasic;
    @XmlElement(name = "PenaltyIP")
    protected String penaltyIP;
    @XmlElement(name = "PenaltySum", required = true)
    protected BigDecimal penaltySum;
    @XmlElement(name = "PenaltyRestTotal", required = true)
    protected BigDecimal penaltyRestTotal;
    @XmlElement(name = "PenaltyKbk", required = true)
    protected String penaltyKbk;
    @XmlElement(name = "PenaltyAuthorName", required = true)
    protected String penaltyAuthorName;
    @XmlElement(name = "PenaltyAuthorTel")
    protected String penaltyAuthorTel;
    @XmlElement(name = "IsConfidential")
    protected boolean isConfidential;

    /**
     * Gets the value of the penaltyKey property.
     * 
     */
    public long getPenaltyKey() {
        return penaltyKey;
    }

    /**
     * Sets the value of the penaltyKey property.
     * 
     */
    public void setPenaltyKey(long value) {
        this.penaltyKey = value;
    }

    /**
     * Gets the value of the ospCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOspCode() {
        return ospCode;
    }

    /**
     * Sets the value of the ospCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOspCode(String value) {
        this.ospCode = value;
    }

    /**
     * Gets the value of the unloadDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUnloadDate() {
        return unloadDate;
    }

    /**
     * Sets the value of the unloadDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUnloadDate(XMLGregorianCalendar value) {
        this.unloadDate = value;
    }

    /**
     * Gets the value of the perpetratorType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerpetratorType() {
        return perpetratorType;
    }

    /**
     * Sets the value of the perpetratorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerpetratorType(String value) {
        this.perpetratorType = value;
    }

    /**
     * Gets the value of the perpetratorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerpetratorName() {
        return perpetratorName;
    }

    /**
     * Sets the value of the perpetratorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerpetratorName(String value) {
        this.perpetratorName = value;
    }

    /**
     * Gets the value of the perpetratorBirthDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPerpetratorBirthDate() {
        return perpetratorBirthDate;
    }

    /**
     * Sets the value of the perpetratorBirthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPerpetratorBirthDate(XMLGregorianCalendar value) {
        this.perpetratorBirthDate = value;
    }

    /**
     * Gets the value of the perpetratorBirthplace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerpetratorBirthplace() {
        return perpetratorBirthplace;
    }

    /**
     * Sets the value of the perpetratorBirthplace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerpetratorBirthplace(String value) {
        this.perpetratorBirthplace = value;
    }

    /**
     * Gets the value of the perpetratorSerDoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerpetratorSerDoc() {
        return perpetratorSerDoc;
    }

    /**
     * Sets the value of the perpetratorSerDoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerpetratorSerDoc(String value) {
        this.perpetratorSerDoc = value;
    }

    /**
     * Gets the value of the perpetratorNumDoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerpetratorNumDoc() {
        return perpetratorNumDoc;
    }

    /**
     * Sets the value of the perpetratorNumDoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerpetratorNumDoc(String value) {
        this.perpetratorNumDoc = value;
    }

    /**
     * Gets the value of the perpetratorSNILS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerpetratorSNILS() {
        return perpetratorSNILS;
    }

    /**
     * Sets the value of the perpetratorSNILS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerpetratorSNILS(String value) {
        this.perpetratorSNILS = value;
    }

    /**
     * Gets the value of the perpetratorINN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerpetratorINN() {
        return perpetratorINN;
    }

    /**
     * Sets the value of the perpetratorINN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerpetratorINN(String value) {
        this.perpetratorINN = value;
    }

    /**
     * Gets the value of the perpetratorKPP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerpetratorKPP() {
        return perpetratorKPP;
    }

    /**
     * Sets the value of the perpetratorKPP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerpetratorKPP(String value) {
        this.perpetratorKPP = value;
    }

    /**
     * Gets the value of the perpetratorOGRN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerpetratorOGRN() {
        return perpetratorOGRN;
    }

    /**
     * Sets the value of the perpetratorOGRN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerpetratorOGRN(String value) {
        this.perpetratorOGRN = value;
    }

    /**
     * Gets the value of the perpetratorAdr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerpetratorAdr() {
        return perpetratorAdr;
    }

    /**
     * Sets the value of the perpetratorAdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerpetratorAdr(String value) {
        this.perpetratorAdr = value;
    }

    /**
     * Gets the value of the perpetratorWorkplace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerpetratorWorkplace() {
        return perpetratorWorkplace;
    }

    /**
     * Sets the value of the perpetratorWorkplace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerpetratorWorkplace(String value) {
        this.perpetratorWorkplace = value;
    }

    /**
     * Gets the value of the perpetratorWorkplaceINN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerpetratorWorkplaceINN() {
        return perpetratorWorkplaceINN;
    }

    /**
     * Sets the value of the perpetratorWorkplaceINN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerpetratorWorkplaceINN(String value) {
        this.perpetratorWorkplaceINN = value;
    }

    /**
     * Gets the value of the perpetratorWorkplaceTelephone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerpetratorWorkplaceTelephone() {
        return perpetratorWorkplaceTelephone;
    }

    /**
     * Sets the value of the perpetratorWorkplaceTelephone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerpetratorWorkplaceTelephone(String value) {
        this.perpetratorWorkplaceTelephone = value;
    }

    /**
     * Gets the value of the perpetratorWorkplaceAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerpetratorWorkplaceAddress() {
        return perpetratorWorkplaceAddress;
    }

    /**
     * Sets the value of the perpetratorWorkplaceAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerpetratorWorkplaceAddress(String value) {
        this.perpetratorWorkplaceAddress = value;
    }

    /**
     * Gets the value of the penaltyNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPenaltyNumber() {
        return penaltyNumber;
    }

    /**
     * Sets the value of the penaltyNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPenaltyNumber(String value) {
        this.penaltyNumber = value;
    }

    /**
     * Gets the value of the penaltyDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPenaltyDate() {
        return penaltyDate;
    }

    /**
     * Sets the value of the penaltyDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPenaltyDate(XMLGregorianCalendar value) {
        this.penaltyDate = value;
    }

    /**
     * Gets the value of the penaltyRiseDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPenaltyRiseDate() {
        return penaltyRiseDate;
    }

    /**
     * Sets the value of the penaltyRiseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPenaltyRiseDate(XMLGregorianCalendar value) {
        this.penaltyRiseDate = value;
    }

    /**
     * Gets the value of the ipBasic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPBasic() {
        return ipBasic;
    }

    /**
     * Sets the value of the ipBasic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPBasic(String value) {
        this.ipBasic = value;
    }

    /**
     * Gets the value of the penaltyBasic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPenaltyBasic() {
        return penaltyBasic;
    }

    /**
     * Sets the value of the penaltyBasic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPenaltyBasic(String value) {
        this.penaltyBasic = value;
    }

    /**
     * Gets the value of the penaltyIP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPenaltyIP() {
        return penaltyIP;
    }

    /**
     * Sets the value of the penaltyIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPenaltyIP(String value) {
        this.penaltyIP = value;
    }

    /**
     * Gets the value of the penaltySum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPenaltySum() {
        return penaltySum;
    }

    /**
     * Sets the value of the penaltySum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPenaltySum(BigDecimal value) {
        this.penaltySum = value;
    }

    /**
     * Gets the value of the penaltyRestTotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPenaltyRestTotal() {
        return penaltyRestTotal;
    }

    /**
     * Sets the value of the penaltyRestTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPenaltyRestTotal(BigDecimal value) {
        this.penaltyRestTotal = value;
    }

    /**
     * Gets the value of the penaltyKbk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPenaltyKbk() {
        return penaltyKbk;
    }

    /**
     * Sets the value of the penaltyKbk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPenaltyKbk(String value) {
        this.penaltyKbk = value;
    }

    /**
     * Gets the value of the penaltyAuthorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPenaltyAuthorName() {
        return penaltyAuthorName;
    }

    /**
     * Sets the value of the penaltyAuthorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPenaltyAuthorName(String value) {
        this.penaltyAuthorName = value;
    }

    /**
     * Gets the value of the penaltyAuthorTel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPenaltyAuthorTel() {
        return penaltyAuthorTel;
    }

    /**
     * Sets the value of the penaltyAuthorTel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPenaltyAuthorTel(String value) {
        this.penaltyAuthorTel = value;
    }

    /**
     * Gets the value of the isConfidential property.
     * 
     */
    public boolean isIsConfidential() {
        return isConfidential;
    }

    /**
     * Sets the value of the isConfidential property.
     * 
     */
    public void setIsConfidential(boolean value) {
        this.isConfidential = value;
    }

}
