//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 12:01:56 PM MSK 
//


package biz.red_soft.schemas.fssp.common._2011._0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Сведения о физическом лице от ФНС
 * 
 * <p>Java class for PersonDatumType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonDatumType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}InformationType">
 *       &lt;sequence>
 *         &lt;element name="INN" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}PersonInnType" minOccurs="0"/>
 *         &lt;element name="birthDate" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}Date" minOccurs="0"/>
 *         &lt;element name="birthPlace" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}String_1_300" minOccurs="0"/>
 *         &lt;element name="OGRNIP" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}OgrnipType" minOccurs="0"/>
 *         &lt;element name="FNSResource" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}FNSResourceType" minOccurs="0"/>
 *         &lt;element name="FIO" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}FioType"/>
 *         &lt;element name="FIOLat" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}FioType" minOccurs="0"/>
 *         &lt;element name="gender" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}GenderCodeType" minOccurs="0"/>
 *         &lt;element name="SNILS" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}SnilsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonDatumType", propOrder = {
    "inn",
    "birthDate",
    "birthPlace",
    "ogrnip",
    "fnsResource",
    "fio",
    "fioLat",
    "gender",
    "snils"
})
public class PersonDatumType
    extends InformationType
{

    @XmlElement(name = "INN")
    protected String inn;
    protected XMLGregorianCalendar birthDate;
    protected String birthPlace;
    @XmlElement(name = "OGRNIP")
    protected String ogrnip;
    @XmlElement(name = "FNSResource")
    protected Integer fnsResource;
    @XmlElement(name = "FIO", required = true)
    protected FioType fio;
    @XmlElement(name = "FIOLat")
    protected FioType fioLat;
    protected String gender;
    @XmlElement(name = "SNILS")
    protected String snils;

    /**
     * Gets the value of the inn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINN() {
        return inn;
    }

    /**
     * Sets the value of the inn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINN(String value) {
        this.inn = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthDate(XMLGregorianCalendar value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the birthPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBirthPlace() {
        return birthPlace;
    }

    /**
     * Sets the value of the birthPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthPlace(String value) {
        this.birthPlace = value;
    }

    /**
     * Gets the value of the ogrnip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOGRNIP() {
        return ogrnip;
    }

    /**
     * Sets the value of the ogrnip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOGRNIP(String value) {
        this.ogrnip = value;
    }

    /**
     * Gets the value of the fnsResource property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFNSResource() {
        return fnsResource;
    }

    /**
     * Sets the value of the fnsResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFNSResource(Integer value) {
        this.fnsResource = value;
    }

    /**
     * Gets the value of the fio property.
     * 
     * @return
     *     possible object is
     *     {@link FioType }
     *     
     */
    public FioType getFIO() {
        return fio;
    }

    /**
     * Sets the value of the fio property.
     * 
     * @param value
     *     allowed object is
     *     {@link FioType }
     *     
     */
    public void setFIO(FioType value) {
        this.fio = value;
    }

    /**
     * Gets the value of the fioLat property.
     * 
     * @return
     *     possible object is
     *     {@link FioType }
     *     
     */
    public FioType getFIOLat() {
        return fioLat;
    }

    /**
     * Sets the value of the fioLat property.
     * 
     * @param value
     *     allowed object is
     *     {@link FioType }
     *     
     */
    public void setFIOLat(FioType value) {
        this.fioLat = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the snils property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSNILS() {
        return snils;
    }

    /**
     * Sets the value of the snils property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSNILS(String value) {
        this.snils = value;
    }

}
