//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 12:01:56 PM MSK 
//


package biz.red_soft.schemas.fssp.common._2011._0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Сведения о субъекте публичного права
 * 
 * <p>Java class for PublicEnityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PublicEnityType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}OrganizationDatumType">
 *       &lt;sequence>
 *         &lt;element name="entityType" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}EntityType"/>
 *         &lt;element name="OKATO" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}OkatoType" minOccurs="0"/>
 *         &lt;element name="regNumber" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}String_1_45" minOccurs="0"/>
 *         &lt;element name="regDate" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}Date" minOccurs="0"/>
 *         &lt;element name="regDateregCountry" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}String_1_255" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PublicEnityType", propOrder = {
    "entityType",
    "okato",
    "regNumber",
    "regDate",
    "regDateregCountry"
})
public class PublicEnityType
    extends OrganizationDatumType
{

    protected long entityType;
    @XmlElement(name = "OKATO")
    protected String okato;
    protected String regNumber;
    protected XMLGregorianCalendar regDate;
    protected String regDateregCountry;

    /**
     * Gets the value of the entityType property.
     * 
     */
    public long getEntityType() {
        return entityType;
    }

    /**
     * Sets the value of the entityType property.
     * 
     */
    public void setEntityType(long value) {
        this.entityType = value;
    }

    /**
     * Gets the value of the okato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOKATO() {
        return okato;
    }

    /**
     * Sets the value of the okato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOKATO(String value) {
        this.okato = value;
    }

    /**
     * Gets the value of the regNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegNumber() {
        return regNumber;
    }

    /**
     * Sets the value of the regNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegNumber(String value) {
        this.regNumber = value;
    }

    /**
     * Gets the value of the regDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRegDate() {
        return regDate;
    }

    /**
     * Sets the value of the regDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRegDate(XMLGregorianCalendar value) {
        this.regDate = value;
    }

    /**
     * Gets the value of the regDateregCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegDateregCountry() {
        return regDateregCountry;
    }

    /**
     * Sets the value of the regDateregCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegDateregCountry(String value) {
        this.regDateregCountry = value;
    }

}
