//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 12:01:56 PM MSK 
//


package biz.red_soft.schemas.fssp.common._2011._0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.w3._2000._09.xmldsig.SignatureType;


/**
 * Документ Query "Запрос СПИ"
 * 
 * <p>Java class for Query complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Query">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InternalKey" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}InternalKeyType"/>
 *         &lt;element name="DocDate" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}Date"/>
 *         &lt;element name="DocNumber" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}DocNumberType" minOccurs="0"/>
 *         &lt;element name="SPI" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}InternalKeyType"/>
 *         &lt;element name="SPIFio" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}FullFioType"/>
 *         &lt;element name="SPIFioParts" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}FioType" minOccurs="0"/>
 *         &lt;element name="SPITel" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}TelephoneNumberType" minOccurs="0"/>
 *         &lt;element name="SPIPost" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}PostType" minOccurs="0"/>
 *         &lt;element name="ChSPIFio" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}FullFioType"/>
 *         &lt;element name="ChSPIFioParts" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}FioType" minOccurs="0"/>
 *         &lt;element name="ChSPIPost" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}PostType"/>
 *         &lt;element name="AnsDate" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}Date"/>
 *         &lt;element name="SearchCountryCode" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}CountryDigitCodeType" minOccurs="0"/>
 *         &lt;element name="SearchCountryName" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}String_1_255" minOccurs="0"/>
 *         &lt;element name="SearchRegion" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}RegionType" minOccurs="0"/>
 *         &lt;element name="SearchYear" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}Year" minOccurs="0"/>
 *         &lt;element name="CreateDate" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}DateTime" minOccurs="0"/>
 *         &lt;element name="DocCode" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}DocumentType" minOccurs="0"/>
 *         &lt;element name="IP" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}IP"/>
 *         &lt;element name="Data" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}Data" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="attachments" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}AttachmentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SignDateTime" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}DateTime" minOccurs="0"/>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Query", propOrder = {
    "internalKey",
    "docDate",
    "docNumber",
    "spi",
    "spiFio",
    "spiFioParts",
    "spiTel",
    "spiPost",
    "chSPIFio",
    "chSPIFioParts",
    "chSPIPost",
    "ansDate",
    "searchCountryCode",
    "searchCountryName",
    "searchRegion",
    "searchYear",
    "createDate",
    "docCode",
    "ip",
    "data",
    "attachments",
    "signDateTime",
    "signature"
})
public class Query {

    @XmlElement(name = "InternalKey")
    protected long internalKey;
    @XmlElement(name = "DocDate", required = true)
    protected XMLGregorianCalendar docDate;
    @XmlElement(name = "DocNumber")
    protected String docNumber;
    @XmlElement(name = "SPI")
    protected long spi;
    @XmlElement(name = "SPIFio", required = true)
    protected String spiFio;
    @XmlElement(name = "SPIFioParts")
    protected FioType spiFioParts;
    @XmlElement(name = "SPITel")
    protected String spiTel;
    @XmlElement(name = "SPIPost")
    protected String spiPost;
    @XmlElement(name = "ChSPIFio", required = true)
    protected String chSPIFio;
    @XmlElement(name = "ChSPIFioParts")
    protected FioType chSPIFioParts;
    @XmlElement(name = "ChSPIPost", required = true)
    protected String chSPIPost;
    @XmlElement(name = "AnsDate", required = true)
    protected XMLGregorianCalendar ansDate;
    @XmlElement(name = "SearchCountryCode")
    protected String searchCountryCode;
    @XmlElement(name = "SearchCountryName")
    protected String searchCountryName;
    @XmlElement(name = "SearchRegion")
    protected String searchRegion;
    @XmlElement(name = "SearchYear")
    protected XMLGregorianCalendar searchYear;
    @XmlElement(name = "CreateDate")
    protected XMLGregorianCalendar createDate;
    @XmlElement(name = "DocCode")
    protected String docCode;
    @XmlElement(name = "IP", required = true)
    protected IP ip;
    @XmlElement(name = "Data")
    protected List<Data> data;
    protected List<AttachmentType> attachments;
    @XmlElement(name = "SignDateTime")
    protected XMLGregorianCalendar signDateTime;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#")
    protected List<SignatureType> signature;

    /**
     * Gets the value of the internalKey property.
     * 
     */
    public long getInternalKey() {
        return internalKey;
    }

    /**
     * Sets the value of the internalKey property.
     * 
     */
    public void setInternalKey(long value) {
        this.internalKey = value;
    }

    /**
     * Gets the value of the docDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDocDate() {
        return docDate;
    }

    /**
     * Sets the value of the docDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDocDate(XMLGregorianCalendar value) {
        this.docDate = value;
    }

    /**
     * Gets the value of the docNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocNumber() {
        return docNumber;
    }

    /**
     * Sets the value of the docNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocNumber(String value) {
        this.docNumber = value;
    }

    /**
     * Gets the value of the spi property.
     * 
     */
    public long getSPI() {
        return spi;
    }

    /**
     * Sets the value of the spi property.
     * 
     */
    public void setSPI(long value) {
        this.spi = value;
    }

    /**
     * Gets the value of the spiFio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPIFio() {
        return spiFio;
    }

    /**
     * Sets the value of the spiFio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPIFio(String value) {
        this.spiFio = value;
    }

    /**
     * Gets the value of the spiFioParts property.
     * 
     * @return
     *     possible object is
     *     {@link FioType }
     *     
     */
    public FioType getSPIFioParts() {
        return spiFioParts;
    }

    /**
     * Sets the value of the spiFioParts property.
     * 
     * @param value
     *     allowed object is
     *     {@link FioType }
     *     
     */
    public void setSPIFioParts(FioType value) {
        this.spiFioParts = value;
    }

    /**
     * Gets the value of the spiTel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPITel() {
        return spiTel;
    }

    /**
     * Sets the value of the spiTel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPITel(String value) {
        this.spiTel = value;
    }

    /**
     * Gets the value of the spiPost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPIPost() {
        return spiPost;
    }

    /**
     * Sets the value of the spiPost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPIPost(String value) {
        this.spiPost = value;
    }

    /**
     * Gets the value of the chSPIFio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChSPIFio() {
        return chSPIFio;
    }

    /**
     * Sets the value of the chSPIFio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChSPIFio(String value) {
        this.chSPIFio = value;
    }

    /**
     * Gets the value of the chSPIFioParts property.
     * 
     * @return
     *     possible object is
     *     {@link FioType }
     *     
     */
    public FioType getChSPIFioParts() {
        return chSPIFioParts;
    }

    /**
     * Sets the value of the chSPIFioParts property.
     * 
     * @param value
     *     allowed object is
     *     {@link FioType }
     *     
     */
    public void setChSPIFioParts(FioType value) {
        this.chSPIFioParts = value;
    }

    /**
     * Gets the value of the chSPIPost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChSPIPost() {
        return chSPIPost;
    }

    /**
     * Sets the value of the chSPIPost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChSPIPost(String value) {
        this.chSPIPost = value;
    }

    /**
     * Gets the value of the ansDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAnsDate() {
        return ansDate;
    }

    /**
     * Sets the value of the ansDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAnsDate(XMLGregorianCalendar value) {
        this.ansDate = value;
    }

    /**
     * Gets the value of the searchCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchCountryCode() {
        return searchCountryCode;
    }

    /**
     * Sets the value of the searchCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchCountryCode(String value) {
        this.searchCountryCode = value;
    }

    /**
     * Gets the value of the searchCountryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchCountryName() {
        return searchCountryName;
    }

    /**
     * Sets the value of the searchCountryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchCountryName(String value) {
        this.searchCountryName = value;
    }

    /**
     * Gets the value of the searchRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchRegion() {
        return searchRegion;
    }

    /**
     * Sets the value of the searchRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchRegion(String value) {
        this.searchRegion = value;
    }

    /**
     * Gets the value of the searchYear property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSearchYear() {
        return searchYear;
    }

    /**
     * Sets the value of the searchYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSearchYear(XMLGregorianCalendar value) {
        this.searchYear = value;
    }

    /**
     * Gets the value of the createDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreateDate() {
        return createDate;
    }

    /**
     * Sets the value of the createDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreateDate(XMLGregorianCalendar value) {
        this.createDate = value;
    }

    /**
     * Gets the value of the docCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocCode() {
        return docCode;
    }

    /**
     * Sets the value of the docCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocCode(String value) {
        this.docCode = value;
    }

    /**
     * Gets the value of the ip property.
     * 
     * @return
     *     possible object is
     *     {@link IP }
     *     
     */
    public IP getIP() {
        return ip;
    }

    /**
     * Sets the value of the ip property.
     * 
     * @param value
     *     allowed object is
     *     {@link IP }
     *     
     */
    public void setIP(IP value) {
        this.ip = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the data property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Data }
     * 
     * 
     */
    public List<Data> getData() {
        if (data == null) {
            data = new ArrayList<Data>();
        }
        return this.data;
    }

    /**
     * Gets the value of the attachments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attachments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttachments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttachmentType }
     * 
     * 
     */
    public List<AttachmentType> getAttachments() {
        if (attachments == null) {
            attachments = new ArrayList<AttachmentType>();
        }
        return this.attachments;
    }

    /**
     * Gets the value of the signDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSignDateTime() {
        return signDateTime;
    }

    /**
     * Sets the value of the signDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSignDateTime(XMLGregorianCalendar value) {
        this.signDateTime = value;
    }

    /**
     * ЭП Gets the value of the signature property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the signature property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSignature().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SignatureType }
     * 
     * 
     */
    public List<SignatureType> getSignature() {
        if (signature == null) {
            signature = new ArrayList<SignatureType>();
        }
        return this.signature;
    }

}
