//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 12:01:56 PM MSK 
//


package biz.red_soft.schemas.fssp.common._2011._0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Ответ на запрос о полученных физическим лицом суммах, взысканных по ИП
 * 
 * <p>Java class for RecoveringIpInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecoveringIpInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Plaintiff" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}ContragentDatumType"/>
 *         &lt;element name="IP" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}IP"/>
 *         &lt;element name="RecoveredAmount" type="{http://www.red-soft.biz/schemas/fssp/common/2011/0.5}RecoveredAmountType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecoveringIpInfoType", propOrder = {
    "plaintiff",
    "ip",
    "recoveredAmount"
})
public class RecoveringIpInfoType {

    @XmlElement(name = "Plaintiff", required = true)
    protected ContragentDatumType plaintiff;
    @XmlElement(name = "IP", required = true)
    protected IP ip;
    @XmlElement(name = "RecoveredAmount")
    protected List<RecoveredAmountType> recoveredAmount;

    /**
     * Gets the value of the plaintiff property.
     * 
     * @return
     *     possible object is
     *     {@link ContragentDatumType }
     *     
     */
    public ContragentDatumType getPlaintiff() {
        return plaintiff;
    }

    /**
     * Sets the value of the plaintiff property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContragentDatumType }
     *     
     */
    public void setPlaintiff(ContragentDatumType value) {
        this.plaintiff = value;
    }

    /**
     * Gets the value of the ip property.
     * 
     * @return
     *     possible object is
     *     {@link IP }
     *     
     */
    public IP getIP() {
        return ip;
    }

    /**
     * Sets the value of the ip property.
     * 
     * @param value
     *     allowed object is
     *     {@link IP }
     *     
     */
    public void setIP(IP value) {
        this.ip = value;
    }

    /**
     * Gets the value of the recoveredAmount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recoveredAmount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecoveredAmount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RecoveredAmountType }
     * 
     * 
     */
    public List<RecoveredAmountType> getRecoveredAmount() {
        if (recoveredAmount == null) {
            recoveredAmount = new ArrayList<RecoveredAmountType>();
        }
        return this.recoveredAmount;
    }

}
